// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package site

import (
	"github.com/kilianc/gsx/internal/gsx/highlight"

	. "maragu.dev/gomponents"

	// Page is one documentation page.
	html "maragu.dev/gomponents/html"
	"strings"
)

type Page struct {
	Slug     string
	Title    string
	Subtitle string
	Body     Node

	// Scripts are script URLs to load at the end of the body, relative to the
	// site root. Only the playground uses this; prose pages stay static.
	Scripts []string
	// Styles are extra stylesheet URLs. The site's own CSS is inlined; this is
	// for vendored CSS too large to inline, like the editor's.
	Styles []string
	// Modules are ES module URLs. The editor bundle is ESM because Monaco is.
	Modules []string
	// Wide drops the sidebar and lets the page use the full window, which an
	// editor beside its output needs and an article does not.
	Wide bool
}

// Layout wraps a page in the site chrome.
func Layout(p Page, pages []Page) Node {
	shell := "shell"
	var sidebar Node
	if p.Wide {
		shell += " shell-wide"
	} else {
		sidebar = Sidebar(p, pages)
	}

	var scripts []Node
	for _, src := range p.Scripts {
		scripts = append(scripts, html.Script(html.Src(src), html.Defer()))
	}

	var styles []Node
	for _, href := range p.Styles {
		styles = append(styles, html.Link(html.Rel("stylesheet"), html.Href(href)))
	}

	// Modules come before the deferred scripts: both wait for parsing, and the
	// controller polls for the editor rather than assuming it has arrived.
	for _, src := range p.Modules {
		scripts = append(scripts, html.Script(html.Type("module"), html.Src(src)))
	}

	var footer Node
	if !p.Wide {
		footer = Footer()
	}

	return Group{
		Raw("<!doctype html>\n"),
		html.HTML(
			html.Lang("en"),
			html.Head(
				html.Meta(html.Charset("utf-8")),
				html.Meta(
					html.Name("viewport"),
					html.Content("width=device-width, initial-scale=1"),
				),
				html.TitleEl(Text(p.Title+" — GSX")),
				html.Meta(html.Name("description"), html.Content(p.Subtitle)),
				html.Link(
					html.Rel("icon"),
					html.Href("./favicon.svg"),
					html.Type("image/svg+xml"),
				),
				El("style", Raw(stylesheet)),
				Group(styles),
			),
			html.Body(
				html.A(html.Class("skip"), html.Href("#content"), Text("Skip to content")),
				Header(),
				html.Div(
					html.Class(shell),
					sidebar,
					html.Main(
						html.ID("content"),
						html.Div(
							html.Class("page-head"),
							html.H1(Text(p.Title)),
							html.P(html.Class("lede"), Text(p.Subtitle)),
						),
						p.Body,
						footer,
					),
				),
				Group(scripts),
			),
		),
	}
}

// Logo is the wordmark: a curly brace whose pinch is an angle bracket, hugging
// the name the way `{ }` hugs a spliced value.
//
// It is inline rather than an <img> so it takes its ink from the surrounding
// text colour, which means it follows the light and dark themes for free. The
// same drawing is in assets/gsx-logo.svg for the README.
func Logo() Node {
	brace := "M32 12 L22 12 L22 32 L10 40 L22 48 L22 68 L32 68"

	return html.SVG(
		html.Class("brand-logo"),
		Attr("viewBox", "0 0 238 80"),
		html.Height("22"),
		html.Role("img"),
		Attr("aria-label", "gsx"),
		El(
			"g",
			Attr("fill", "none"),
			Attr("stroke-width", "8"),
			Attr("stroke-linecap", "round"),
			Attr("stroke-linejoin", "round"),
			html.Class("brand-braces"),
			El("path", Attr("d", brace)),
			El("path", Attr("d", brace), Attr("transform", "translate(238,0) scale(-1,1)")),
		),
		El(
			"g",
			Attr("fill", "none"),
			Attr("stroke", "currentColor"),
			Attr("stroke-width", "8"),
			Attr("stroke-linecap", "round"),
			Attr("stroke-linejoin", "round"),
			El("circle", Attr("cx", "78"), Attr("cy", "40"), Attr("r", "14")),
			El("path", Attr("d", "M92 26 L92 58 C92 68 84 71 75 67")),
			El(
				"path",
				Attr(
					"d",
					"M134 32 C134 24 110 24 110 33 C110 41 134 39 134 47 C134 56 110 56 110 48",
				),
			),
			El("path", Attr("d", "M150 26 L174 54")),
			El("path", Attr("d", "M174 26 L150 54")),
		),
	)
}

func Header() Node {
	return html.Header(
		html.Class("topbar"),
		html.A(
			html.Class("brand"),
			html.Href("./index.html"),
			Attr("aria-label", "GSX home"),
			Logo(),
		),
		html.Nav(
			html.Class("topnav"),
			html.A(html.Href("./playground.html"), Text("Playground")),
			html.A(html.Href("./language.html"), Text("Language")),
			html.A(html.Href("./components.html"), Text("Components")),
			html.A(html.Href("./live-reload.html"), Text("Live reload")),
			html.A(html.Href("./editors.html"), Text("Editors")),
			html.A(
				html.Class("ext"),
				html.Href("https://github.com/kilianc/gsx"),
				Text("GitHub"),
			),
		),
	)
}

func Sidebar(current Page, pages []Page) Node {
	var links []Node
	for _, p := range pages {
		cls := "side-link"
		if p.Slug == current.Slug {
			cls += " is-current"
		}
		links = append(links, html.Li(
			html.A(html.Class(cls), html.Href("./"+p.Slug+".html"), Text(p.Title)),
		))
	}
	return html.Aside(
		html.Class("sidebar"),
		html.Nav(
			html.P(html.Class("side-title"), Text("Documentation")),
			html.Ul(Group(links)),
		),
	)
}

func Footer() Node {
	return html.Footer(
		html.Class("footer"),
		html.P(
			Text(
				"GSX is generated ahead of time — the output is plain, readable Go using",
			),
			Text(" "),
			html.A(
				html.Href("https://pkg.go.dev/maragu.dev/gomponents"),
				Text("gomponents"),
			),
			Text("."),
		),
		html.P(html.Class("muted"), Text("This site is itself written in GSX.")),
	)
}

// Section is a documentation section with a linkable heading.
func Section(id string, title string, children ...Node) Node {
	return html.Section(
		html.Class("section"),
		html.ID(id),
		html.H2(html.A(html.Class("anchor"), html.Href("#"+id), Text(title))),
		Group(children),
	)
}

func P(children ...Node) Node  { return El("p", Group(children)) }
func Em(s string) Node         { return El("em", Text(s)) }
func Strong(s string) Node     { return El("strong", Text(s)) }
func Link(href, s string) Node { return html.A(html.Href(href), Text(s)) }

// Code renders an inline code span.
func Code(s string) Node { return El("code", Text(s)) }

// GSX renders a highlighted GSX or Go snippet.
//
// The highlighter understands tag expressions and the `{...}` boundary, which
// is exactly what a reader needs to see on a page explaining that boundary.
func GSX(src string) Node {
	return codeBlock("gsx", highlight.HTML(strings.TrimSpace(src)))
}

// Out renders generated output or rendered HTML, shown unhighlighted so it
// reads as a result rather than as something to write.
func Out(label, src string) Node {
	return codeBlock("out", `<span class="hl-out-label">`+label+`</span>`+htmlEscape(strings.TrimSpace(src)))
}

// Shell renders a terminal command.
func Shell(src string) Node {
	return codeBlock("sh", htmlEscape(strings.TrimSpace(src)))
}

func codeBlock(kind, inner string) Node {
	return html.Div(html.Class("code code-"+kind), El("pre", El("code", Raw(inner))))
}

// Split shows source and its result side by side, which is the clearest way to
// present a compiler.
func Split(left, right Node) Node {
	return html.Div(html.Class("split"), html.Div(left), html.Div(right))
}

// Note renders an aside.
func Note(children ...Node) Node {
	return html.Div(html.Class("note"), Group(children))
}

func htmlEscape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;")
	return r.Replace(s)
}
