// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package site

import (
	"fmt"

	. "maragu.dev/gomponents"
	html "maragu.dev/gomponents/html"
	"strconv"
	"strings"
	"time"
)

// repo is where the releases, tags and pull requests linked from this page live.
const repo = "https://github.com/kilianc/gsx"

func ReleasesPage() Page {
	releases := Releases()

	var sections []Node
	for i, r := range releases {
		sections = append(sections, releaseSection(r, i == 0))
	}

	return Page{
		Slug:     "releases",
		Title:    "Releases",
		Subtitle: "Every tagged version, what changed in it, and what is on main that no tag carries yet.",
		Body: Group{
			releaseIndex(releases),
			Section(
				"install",
				"Installing a version",
				P(
					Text("The CLI is a Go program, so "),
					Code("go install"),
					Text(" is the whole story. "),
					Code("@latest"),
					Text(" follows the newest tag:"),
				),
				Shell("go install "+strings.TrimPrefix(repo, "https://")+"/cmd/gsx@latest"),
				P(Text("Pin the version when a build has to keep producing the same output:")),
				Shell(
					"go install "+strings.TrimPrefix(repo, "https://")+"/cmd/gsx@"+Latest().Version,
				),
				P(
					Text("Every release below carries a "),
					Code(".vsix"),
					Text(" of the editor extension as an asset — "),
					Link("./editors.html", "installing it"),
					Text(" is on the editors page. The extension runs the "),
					Code("gsx"),
					Text(" binary, so install the CLI first."),
				),
				Note(
					P(
						Text("Generated "),
						Code(".gsx.go"),
						Text(" files are checked in, so upgrading the compiler is a "),
						Code("gsx ./..."),
						Text(
							" and a diff you can read. If the generated output changed, the release notes say so.",
						),
					),
				),
			),
			unreleasedSection(),
			Group(sections),
		},
	}
}

// releaseIndex is the jump list under the page head. It earns its place as the
// history grows: the entries themselves are long enough that the shape of the
// list is not visible from any one of them.
func releaseIndex(releases []Release) Node {
	var pills []Node
	if len(Unreleased()) > 0 {
		pills = append(pills, html.A(html.Class("release-pill"), html.Href("#unreleased"), Text("on main")))
	}
	for _, r := range releases {
		pills = append(pills, html.A(
			html.Class("release-pill"),
			html.Href("#"+anchorID(r.Version)),
			Text(r.Version),
		))
	}
	return html.Nav(
		html.Class("release-index"),
		Attr("aria-label", "Versions"),
		Group(pills),
	)
}

// unreleasedSection lists what main carries beyond the newest tag. It is
// rendered from the same Change type as a release so the entries do not have to
// be rewritten when they become part of one.
func unreleasedSection() Node {
	changes := Unreleased()
	if len(changes) == 0 {
		return nil
	}

	return html.Section(
		html.Class("section release"),
		html.ID("unreleased"),
		html.Div(
			html.Class("release-head"),
			html.H2(html.A(html.Class("anchor"), html.Href("#unreleased"), Text("On main"))),
			html.Span(html.Class("release-badge release-badge-open"), Text("unreleased")),
			html.A(
				html.Class("release-date ext"),
				html.Href(repo+"/compare/"+Latest().Version+"...main"),
				Text("since "+Latest().Version),
			),
		),
		html.P(
			html.Class("release-summary"),
			Text(
				"Merged and deployed — this site is built from main — but not yet in a tag. To run it, install from ",
			),
			html.Code(Text("@main")),
			Text(" rather than "),
			html.Code(Text("@latest")),
			Text("."),
		),
		Group(changeNodes(changes)),
	)
}

// releaseSection renders one tagged release: what it is, what changed, and the
// links back to the tag it came from.
func releaseSection(r Release, latest bool) Node {
	id := anchorID(r.Version)

	var badge Node
	if latest {
		badge = html.Span(html.Class("release-badge"), Text("latest"))
	}

	links := []Node{
		html.A(
			html.Class("ext"),
			html.Href(repo+"/releases/tag/"+r.Version),
			Text("Release notes and downloads"),
		),
	}
	if r.Previous != "" {
		links = append(links, html.A(
			html.Class("ext"),
			html.Href(repo+"/compare/"+r.Previous+"..."+r.Version),
			Text("Every commit since "+r.Previous),
		))
	}

	return html.Section(
		html.Class("section release"),
		html.ID(id),
		html.Div(
			html.Class("release-head"),
			html.H2(html.A(html.Class("anchor"), html.Href("#"+id), Text(r.Version))),
			badge,
			html.Time(
				html.Class("release-date"),
				html.DateTime(r.Date),
				Text(humanDate(r.Date)),
			),
		),
		html.P(html.Class("release-summary"), prose(r.Summary)),
		Group(changeNodes(r.Changes)),
		html.P(html.Class("release-links"), Group(links)),
	)
}

func changeNodes(changes []Change) []Node {
	var out []Node
	for _, c := range changes {
		out = append(out, html.H3(prose(c.Title), Group(refLinks(c.Refs))))
		for _, para := range c.Body {
			out = append(out, html.P(prose(para)))
		}
	}
	return out
}

func refLinks(refs []int) []Node {
	var out []Node
	for _, n := range refs {
		out = append(out, html.A(
			html.Class("release-ref"),
			html.Href(fmt.Sprintf("%s/pull/%d", repo, n)),
			Text("#"+strconv.Itoa(n)),
		))
	}
	return out
}

// prose renders a note, setting runs between backticks as inline code.
//
// That is deliberately the whole of the markup a note may carry: the entries
// are prose about code, and anything that wants more than an identifier set in
// mono belongs on a documentation page the note can link to.
func prose(s string) Node {
	var out []Node
	for i, part := range strings.Split(s, "`") {
		if part == "" {
			continue
		}
		if i%2 == 1 {
			out = append(out, html.Code(Text(part)))
			continue
		}
		out = append(out, Text(part))
	}
	return Group(out)
}

// anchorID turns a version into a fragment. The dots are dropped because a
// fragment carrying them is awkward to select and to quote, not because it
// would be invalid.
func anchorID(version string) string {
	return strings.ReplaceAll(version, ".", "-")
}

// humanDate renders a stored YYYY-MM-DD for reading. A malformed date is shown
// as it was written rather than failing the build: the date is the least
// load-bearing thing on the page.
func humanDate(iso string) string {
	t, err := time.Parse("2006-01-02", iso)
	if err != nil {
		return iso
	}
	return t.Format("2 January 2006")
}
