// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package site

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func LiveReloadPage() Page {
	return Page{
		Slug:     "live-reload",
		Title:    "Live reload",
		Subtitle: "Save a file, see the change. gsx dev regenerates, restarts your server and reloads the browser.",
		Body: Group{
			Section(
				"start",
				"Start it",
				Shell("gsx dev"),
				P(Text("Then open "), Code("http://localhost:8080"), Text(".")),
				P(
					Text("On every save GSX regenerates the changed "),
					Code(".gsx"),
					Text(
						" files, restarts your app, waits for it to accept connections, and only then reloads the browser.",
					),
				),
				Note(
					P(
						Text(
							"The wait matters. A Go server has to be rebuilt and restarted before a refresh can show anything new, so a reload fired the moment a file changed would land on a stale process. This is why ",
						),
						Code("gsx dev"),
						Text(" supervises your application rather than only watching files."),
					),
				),
			),
			Section(
				"config",
				"Configuration",
				Shell(
					`gsx dev \
  -run "go run ./cmd/server" \
  -app-addr localhost:3000 \
  -addr localhost:8080`,
				),
				html.Table(
					html.THead(
						html.Tr(
							html.Th(Text("Flag")),
							html.Th(Text("Default")),
							html.Th(Text("Meaning")),
						),
					),
					html.TBody(
						html.Tr(
							html.Td(html.Code(Text("-run"))),
							html.Td(html.Code(Text("go run ."))),
							html.Td(Text("Command that builds and starts your app")),
						),
						html.Tr(
							html.Td(html.Code(Text("-app-addr"))),
							html.Td(html.Code(Text("localhost:3000"))),
							html.Td(Text("Where your app listens")),
						),
						html.Tr(
							html.Td(html.Code(Text("-addr"))),
							html.Td(html.Code(Text("localhost:8080"))),
							html.Td(Text("Where to point your browser")),
						),
						html.Tr(
							html.Td(html.Code(Text("-dir"))),
							html.Td(Text("current directory")),
							html.Td(Text("Directory to watch")),
						),
						html.Tr(
							html.Td(html.Code(Text("-debounce"))),
							html.Td(html.Code(Text("120ms"))),
							html.Td(Text("How long to let file events settle")),
						),
					),
				),
			),
			Section(
				"noconfig",
				"Your app needs no changes",
				P(
					Text(
						"The reload client is injected by a reverse proxy on the way through, not rendered by your code. Nothing in your application refers to GSX, and a production build cannot accidentally ship a development client.",
					),
				),
				P(
					Text("Requests to "),
					Code("-addr"),
					Text(" are forwarded to "),
					Code("-app-addr"),
					Text(". HTML responses get a small script appended before "),
					Code("</body>"),
					Text("; everything else is passed through untouched."),
				),
			),
			Section(
				"errors",
				"Build failures",
				P(
					Text(
						"A failed build is pushed to the browser as a full-page overlay carrying the same message the terminal shows:",
					),
				),
				Out(
					"overlay",
					`
GSX build failed

app/page.gsx:7:22: mismatched closing tag </h2>, expected </h1>

  7 |     <h1>version three</h2>
    |                      ^
`,
				),
				P(
					Text("The overlay stays until the next successful build. A tab opened "),
					Em("while"),
					Text(" the build is broken is shown the error too, rather than a blank page."),
				),
				P(
					Text(
						"While the app restarts, the proxy serves a placeholder that also carries the reload client, so a tab that lands mid-restart recovers on its own instead of showing a browser error.",
					),
				),
			),
			Section(
				"ci",
				"Generation in CI",
				P(Text("Generated files are checked in, so CI should verify they are current:")),
				Shell("gsx -check ./..."),
				P(
					Text("It writes nothing and exits non-zero listing any stale file, so a "),
					Code(".gsx"),
					Text(" edit can never land without its regenerated "),
					Code(".gsx.go"),
					Text("."),
				),
			),
		},
	}
}

func EditorsPage() Page {
	return Page{
		Slug:     "editors",
		Title:    "Editors",
		Subtitle: "A gopls-backed language server gives .gsx files the Go tooling you already use.",
		Body: Group{
			Section(
				"how",
				"How it works",
				P(
					Text("GSX ships a language server that sits between your editor and "),
					Code("gopls"),
					Text(". It compiles the "),
					Code(".gsx"),
					Text(
						" buffer to a virtual Go view, forwards the request, and maps positions back — so diagnostics, hover and go-to-definition land on the code you wrote, not on generated output.",
					),
				),
				html.Ul(
					html.Li(Text("Diagnostics, including type errors from the generated code")),
					html.Li(Text("Hover")),
					html.Li(Text("Go to definition")),
					html.Li(Text("Completion for Go expressions")),
				),
				P(
					Text(
						"Some requests GSX answers itself, because gopls cannot: it has no notion of a tag name, and the generated Go view is not what you are editing.",
					),
				),
				html.Ul(
					html.Li(
						html.Strong(Text("Tag completion")),
						Text(" after "),
						html.Code(Text("<")),
						Text(" — components defined in the file first, then HTML elements"),
					),
					html.Li(
						html.Strong(Text("Attribute completion")),
						Text(
							" inside a start tag, including the JSX spellings, with the caret landing between the quotes",
						),
					),
					html.Li(
						html.Strong(Text("Closing tags")),
						Text(" after "),
						html.Code(Text("</")),
						Text(", naming whichever tag is still open"),
					),
					html.Li(html.Strong(Text("Formatting")), Text(", so format-on-save works")),
				),
				P(
					Text(
						"GSX's own parse errors are reported directly, positioned on the offending character.",
					),
				),
				Note(
					P(
						Text(
							"Completion works on a buffer that does not parse — which is the normal state while typing ",
						),
						Code("<Car"),
						Text(
							". It scans rather than parses for exactly that reason: parsing would mean offering nothing at the moment you are asking.",
						),
					),
				),
			),
			Section(
				"editing",
				"Editing",
				P(
					Text(
						"The extension adds the editing behaviour a JSX-like language needs, none of which can come from the language server — it has to react to a keystroke before the buffer is parseable:",
					),
				),
				html.Ul(
					html.Li(
						html.Strong(Text("Auto-close tags.")),
						Text(" Typing "),
						html.Code(Text(">")),
						Text(
							" inserts the matching closing tag and leaves the caret between them. Void elements and self-closing tags are left alone.",
						),
					),
					html.Li(
						html.Strong(Text("Linked editing.")),
						Text(" Renaming an opening tag renames its closing tag as you type."),
					),
					html.Li(
						html.Strong(Text("Snippets.")),
						Text(" "),
						html.Code(Text("comp")),
						Text(", "),
						html.Code(Text("layout")),
						Text(", "),
						html.Code(Text("frag")),
						Text(", "),
						html.Code(Text("each")),
						Text(", "),
						html.Code(Text("if")),
						Text(" and friends."),
					),
					html.Li(
						html.Strong(Text("Indentation.")),
						Text(
							" Pressing enter between a tag pair indents the body and puts the closing tag on its own line.",
						),
					),
					html.Li(
						html.Strong(Text("File nesting.")),
						Text(" Generated "),
						html.Code(Text(".gsx.go")),
						Text(" files collapse under their source."),
					),
				),
				P(
					Text(
						"Syntax highlighting understands the boundary between Go and markup: components are coloured differently from HTML elements, prose between tags is not highlighted as Go, and a comparison like ",
					),
					Code("a < b"),
					Text(" is never mistaken for a tag."),
				),
				html.H3(Text("Formatting")),
				P(
					Text("The language server formats "),
					Code(".gsx"),
					Text(
						" buffers, so format-on-save works. The same formatter runs on the command line:",
					),
				),
				Shell("gsx fmt -w ./..."),
				P(
					Text(
						"Go code is formatted exactly as gofmt would format it. Markup keeps the shape you gave it and is only re-indented to match its surroundings — the formatter deliberately does not reflow attributes or move children onto their own lines.",
					),
				),
				P(
					Text("Use "),
					Code("gsx fmt -l ./..."),
					Text(" in CI to fail on unformatted sources, and "),
					Code("gsx fmt -d"),
					Text(" to see the diff."),
				),
				html.H3(Text("Commands")),
				html.Table(
					html.THead(html.Tr(html.Th(Text("Command")), html.Th(Text("Does")))),
					html.TBody(
						html.Tr(
							html.Td(Text("GSX: Generate All")),
							html.Td(html.Code(Text("gsx ./...")), Text(" in a terminal")),
						),
						html.Tr(
							html.Td(Text("GSX: Generate Current File")),
							html.Td(Text("regenerate just this file")),
						),
						html.Tr(
							html.Td(Text("GSX: Start Dev Server")),
							html.Td(html.Code(Text("gsx dev"))),
						),
						html.Tr(
							html.Td(Text("GSX: Open Generated Go File")),
							html.Td(
								Text("open the "),
								html.Code(Text(".gsx.go")),
								Text(" beside the editor ("),
								html.Code(Text("alt+o")),
								Text(")"),
							),
						),
						html.Tr(
							html.Td(Text("GSX: Restart Language Server")),
							html.Td(Text("restart "), html.Code(Text("gsx lsp"))),
						),
					),
				),
			),
			Section(
				"vscode",
				"VS Code and Cursor",
				P(
					Text("Install the extension from "),
					Code("vscode/gsx-vscode/"),
					Text(", and make sure "),
					Code("gsx"),
					Text(" is on your "),
					Code("PATH"),
					Text(":"),
				),
				Shell("go install github.com/kilianc/gsx/cmd/gsx@latest"),
				P(
					Text("The extension starts "),
					Code("gsx lsp"),
					Text(" for every "),
					Code(".gsx"),
					Text(" file."),
				),
				P(
					Text(
						"Building it needs Node, which GSX itself does not. The toolchain is pinned in ",
					),
					Code("tools/Dockerfile"),
					Text(", so no JS toolchain is installed on your machine:"),
				),
				Shell("make vsix"),
				Note(
					P(
						Text("On macOS, "),
						Code("gsx"),
						Text(" collides with Ghostscript's "),
						Code("gsx"),
						Text(" if that is installed. The extension prefers a workspace-local "),
						Code("./bin/gsx"),
						Text(" and the usual Go install paths before falling back to "),
						Code("PATH"),
						Text("; you can also set "),
						Code("gsx.executablePath"),
						Text(" explicitly."),
					),
				),
			),
			Section(
				"minimal",
				"Highlighting only",
				P(
					Text("Without the extension, treating "),
					Code(".gsx"),
					Text(" as Go gives you syntax highlighting that is close enough to read:"),
				),
				Out(
					"settings.json",
					`
{
  "files.associations": {
    "*.gsx": "go"
  }
}
`,
				),
				P(
					Text(
						"Tag expressions will be highlighted as Go rather than as markup, and gopls will report the tags as syntax errors — this is a stopgap, not a setup.",
					),
				),
			),
			Section(
				"api",
				"Embedding the compiler",
				P(Text("To compile "), Code(".gsx"), Text(" from your own tooling:")),
				GSX(
					`
import "github.com/kilianc/gsx/pkg/gsx"

out, err := gsx.CompileFile("page.gsx", src)
`,
				),
				P(
					Text("The internal compiler under "),
					Code("internal/gsx/..."),
					Text(" is not part of the public API."),
				),
			),
		},
	}
}
