// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package site

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func IndexPage() Page {
	return Page{
		Slug:     "index",
		Title:    "GSX",
		Subtitle: "JSX for Go. Write markup inline in ordinary Go functions — with real loops, conditionals and calls in the middle of it. No template language, no runtime.",
		Body: Group{
			html.Div(
				html.Class("hero-cta"),
				html.A(
					html.Class("btn btn-primary"),
					html.Href("./language.html"),
					Text("Read the language guide"),
				),
				html.A(
					html.Class("btn"),
					html.Href("./playground.html"),
					Text("Try it in the playground"),
				),
				html.A(
					html.Class("btn"),
					html.Href("https://github.com/kilianc/gsx"),
					Text("GitHub"),
				),
			),
			Shell("go install github.com/kilianc/gsx/cmd/gsx@latest"),
			Section(
				"jsx",
				"If you know JSX, you already know GSX",
				P(
					Text("A "),
					Code(".gsx"),
					Text(
						" file is a normal Go file. The only new thing is the one JSX added to JavaScript: ",
					),
					Strong("a tag is an expression"),
					Text(". Here is the same component in both languages."),
				),
				Split(
					Labeled(
						"javascript · jsx",
						`
function ProfileCard({ name, tags, admin }) {
  return (
    <section className="card">
      <header>
        <h2>{name.trim()}</h2>
        {admin && <span className="pill">admin</span>}
      </header>
      <ul className="tags">
        {tags.map((t) => <li className="tag">{t}</li>)}
      </ul>
    </section>
  );
}
`,
					),
					Labeled(
						"go · gsx",
						`
func ProfileCard(name string, tags []string, admin bool) Node {
  var lis []Node
  for _, t := range tags {
    lis = append(lis, <li class="tag">{t}</li>)
  }

  return (
    <section class="card">
      <header>
        <h2>{strings.TrimSpace(name)}</h2>
        {If(admin, <span class="pill">admin</span>)}
      </header>
      <ul class="tags">{lis}</ul>
    </section>
  )
}
`,
					),
				),
				P(
					Text("Same shape, same instincts. Tags, fragments, "),
					Code("{expr}"),
					Text(" splices, "),
					Code("className"),
					Text(", spread attributes, "),
					Code("{/* comments */}"),
					Text(" — the syntax carries over."),
				),
				P(
					Text("What changes is the language "),
					Em("around"),
					Text(" the tags. "),
					Code("map"),
					Text(" becomes a "),
					Code("for"),
					Text(" loop, "),
					Code("&&"),
					Text(" becomes "),
					Code("If"),
					Text(", and props are typed function parameters instead of an untyped object."),
				),
			),
			Section(
				"go",
				"Real Go, right in the middle of the markup",
				P(
					Text(
						"This is the whole point. Because a tag is an expression, markup sits inside ordinary Go control flow, ",
					),
					Text(
						"and Go control flow sits inside markup. Nothing is a special template directive — it is the language you already write.",
					),
				),
				html.Ul(
					html.Li(
						html.Code(Text("for")),
						Text(" and "),
						html.Code(Text("range")),
						Text(" build lists into a "),
						html.Code(Text("[]Node")),
						Text("."),
					),
					html.Li(
						html.Code(Text("if")),
						Text(", "),
						html.Code(Text("switch")),
						Text(" and early "),
						html.Code(Text("return")),
						Text(" pick between branches of markup."),
					),
					html.Li(
						Text("Function and method calls fill in values, and any function returning "),
						html.Code(Text("Node")),
						Text(" is a component."),
					),
					html.Li(
						Text(
							"Variables hold markup, so you can build a piece of a page before you place it.",
						),
					),
				),
				CompiledBelow(
					`
func InvoiceTable(invoices []Invoice) Node {
  if len(invoices) == 0 {
    return <p class="empty">No invoices yet.</p>
  }

  var rows []Node
  for _, inv := range invoices {
    rows = append(rows, (
      <tr>
        <td>{inv.Number}</td>
        <td>{inv.Customer.Name}</td>
        <td class="num">{money(inv.Total)}</td>
        <td>{StatusPill(inv.Status)}</td>
      </tr>
    ))
  }

  return (
    <table class="invoices">
      <tbody>{rows}</tbody>
    </table>
  )
}

func StatusPill(s Status) Node {
  switch s {
  case Paid:
    return <span class="pill pill-ok">paid</span>
  case Overdue:
    return <span class="pill pill-bad">overdue</span>
  }
  return <span class="pill">draft</span>
}
`,
				),
				P(
					Text("There is no template language between you and the page — no "),
					Code("{{range}}"),
					Text(
						", no partials to register, no separate file to keep in sync. The empty-state check is a plain ",
					),
					Code("if"),
					Text(", and the status pill is a plain "),
					Code("switch"),
					Text("."),
				),
				P(
					Text(
						"Props are function parameters, so a typo is a compile error, your editor completes them from the signature, ",
					),
					Text("and a rename refactors every call site."),
				),
			),
			Section(
				"translate",
				"Coming from JSX",
				P(
					Text(
						"Most of what you know transfers directly. The rest has an obvious Go spelling:",
					),
				),
				html.Table(
					html.THead(html.Tr(html.Th(Text("JSX")), html.Th(Text("GSX")))),
					html.TBody(
						html.Tr(
							html.Td(
								html.Code(Text("<div>…</div>")),
								Text(", "),
								html.Code(Text("<>…</>")),
								Text(", "),
								html.Code(Text("{expr}")),
							),
							html.Td(Text("identical")),
						),
						html.Tr(
							html.Td(
								html.Code(Text("className")),
								Text(", "),
								html.Code(Text("htmlFor")),
								Text(", "),
								html.Code(Text("maxLength")),
							),
							html.Td(Text("identical (or the HTML spelling, your choice)")),
						),
						html.Tr(
							html.Td(html.Code(Text("{items.map(i => <li>{i}</li>)}"))),
							html.Td(
								Text("a "),
								html.Code(Text("for")),
								Text(" loop appending to "),
								html.Code(Text("[]Node")),
								Text(", spliced"),
							),
						),
						html.Tr(
							html.Td(html.Code(Text("{cond && <p/>}"))),
							html.Td(
								html.Code(Text("{If(cond, <p/>)}")),
								Text(", or plain Go "),
								html.Code(Text("if")),
							),
						),
						html.Tr(
							html.Td(html.Code(Text("{...props}"))),
							html.Td(
								html.Code(Text("{...attrs}")),
								Text(", where "),
								html.Code(Text("attrs")),
								Text(" is a "),
								html.Code(Text("[]Node")),
							),
						),
						html.Tr(
							html.Td(Text("a props object")),
							html.Td(Text("typed function parameters")),
						),
						html.Tr(
							html.Td(html.Code(Text("children"))),
							html.Td(Text("a trailing "), html.Code(Text("...Node")), Text(" parameter")),
						),
						html.Tr(
							html.Td(html.Code(Text("<Card/>")), Text(" resolved by scope")),
							html.Td(Text("uppercase tags are function calls, resolved lexically")),
						),
						html.Tr(
							html.Td(Text("hooks, state, a virtual DOM")),
							html.Td(Text("none of it — GSX only renders")),
						),
					),
				),
				P(
					Text(
						"GSX is the JSX half of the deal: the syntax, on the server, ahead of time. ",
					),
					Text(
						"For interactivity, reach for whatever you would otherwise pair with server-rendered HTML.",
					),
				),
			),
			Section(
				"output",
				"No runtime — the generated Go is the artifact",
				P(
					Text("GSX runs ahead of time and writes a "),
					Code(".gsx.go"),
					Text(" file next to each source file. "),
					Text("You check it in and review it like any other code — as the "),
					Code("InvoiceTable"),
					Text(" output above shows, it is the same function with the tags spelled out."),
				),
				P(
					Text(
						"When something renders wrong, you open that file and read exactly what will run. ",
					),
					Text(
						"No reflection, no template parser, no interpreter, no diffing — at run time it is ordinary ",
					),
					Link("https://pkg.go.dev/maragu.dev/gomponents", "gomponents"),
					Text(" calls you can step through in a debugger."),
				),
				Note(
					P(
						Text(
							"Nothing GSX-specific ships in your binary. The compiler is a build-time tool, so a production build ",
						),
						Text("cannot depend on it and cannot drift from it — "),
						Code("gsx -check ./..."),
						Text(" proves that in CI."),
					),
				),
			),
			Section(
				"why",
				"What you get",
				html.Div(
					html.Class("cards"),
					html.Div(
						html.Class("card"),
						html.H3(Text("JSX syntax, Go semantics")),
						html.P(
							Text(
								"Tags, fragments, splices and spread work the way you expect. Everything between them is Go, checked by the Go compiler.",
							),
						),
					),
					html.Div(
						html.Class("card"),
						html.H3(Text("Loops and branches, not directives")),
						html.P(
							html.Code(Text("for")),
							Text(", "),
							html.Code(Text("if")),
							Text(", "),
							html.Code(Text("switch")),
							Text(" and early returns build markup, because a tag is just an expression."),
						),
					),
					html.Div(
						html.Class("card"),
						html.H3(Text("Type-safe by construction")),
						html.P(
							Text(
								"Components are functions and props are parameters, so the compiler checks every call site and your editor completes them.",
							),
						),
					),
					html.Div(
						html.Class("card"),
						html.H3(Text("The output is the artifact")),
						html.P(
							Text(
								"Generated files are readable Go you check in and review. Debugging is reading code, not tracing a template engine.",
							),
						),
					),
					html.Div(
						html.Class("card"),
						html.H3(Text("Live reload")),
						html.P(
							html.Code(Text("gsx dev")),
							Text(
								" regenerates, restarts your server and reloads the browser on every save.",
							),
						),
					),
					html.Div(
						html.Class("card"),
						html.H3(Text("Real editor support")),
						html.P(
							Text(
								"A gopls-backed language server gives diagnostics, hover and go-to-definition inside ",
							),
							html.Code(Text(".gsx")),
							Text(" files."),
						),
					),
				),
			),
			Section(
				"start",
				"Getting started",
				P(Text("Write a "), Code(".gsx"), Text(" file, then generate:")),
				Shell("gsx ./..."),
				P(Text("In CI, check that source and generated output never drift apart:")),
				Shell("gsx -check ./..."),
				P(Text("While developing, get a rebuild and a browser reload on every save:")),
				Shell("gsx dev"),
				P(
					Text("Next: "),
					Link("./language.html", "the language reference"),
					Text(", or "),
					Link("./composition.html", "how to build and organize components"),
					Text("."),
				),
			),
		},
	}
}
