// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package site

import

// example is what the playground opens with. It is deliberately a little more
// than "hello": a loop, a conditional and a splice calling into Go are the
// things a reader is actually trying to find out about.
(
	. "maragu.dev/gomponents"
	html "maragu.dev/gomponents/html"
)

const example = `package main

import "fmt"

type Product struct {
	Name  string
	Price float64
	Sale  bool
}

// Page is the entry point. The playground renders whatever it returns.
func Page() Node {
	products := []Product{
		{"Keyboard", 89.99, true},
		{"Monitor", 329.50, false},
		{"Desk mat", 24.00, false},
	}

	var rows []Node
	for _, p := range products {
		class := "row"
		if p.Sale {
			class += " on-sale"
		}

		rows = append(rows, (
			<tr class={class}>
				<td>{p.Name}</td>
				<td>{fmt.Sprintf("$%.2f", p.Price)}</td>
				<td>{badge(p.Sale)}</td>
			</tr>
		))
	}

	return (
		<table class="cart">
			<thead>
				<tr><th>Item</th><th>Price</th><th></th></tr>
			</thead>
			<tbody>{rows}</tbody>
		</table>
	)
}

func badge(sale bool) Node {
	if !sale {
		return nil
	}
	return <span class="badge">Sale</span>
}
`

func PlaygroundPage() Page {
	return Page{
		Slug:     "playground",
		Title:    "Playground",
		Subtitle: "Write GSX on the left. The Go it compiles to, and the HTML that Go renders, appear on the right.",
		Wide:     true,
		Styles:   []string{"./vendor/editor.css"},
		Modules:  []string{"./vendor/editor.js"},
		Scripts:  []string{"./playground.js"},
		Body: Group{
			html.Div(
				html.Class("pg"),
				html.Div(
					html.Class("pg-col"),
					html.Div(
						html.Class("pg-bar"),
						html.Span(html.Class("pg-label"), Text("page.gsx")),
						html.Span(
							html.ID("pg-status"),
							html.Class("pg-status is-busy"),
							Text("Loading compiler…"),
						),
					),
					html.Div(html.ID("pg-mount"), html.Class("pg-mount")),
					El(
						"textarea",
						Attr("id", "pg-editor"),
						Attr("class", "pg-editor"),
						Attr("spellcheck", "false"),
						Attr("autocomplete", "off"),
						Attr("autocapitalize", "off"),
						Attr("aria-label", "GSX source"),
						Text(example),
					),
				),
				html.Div(
					html.Class("pg-col"),
					html.Div(
						html.Class("pg-bar"),
						html.Button(
							html.Class("pg-tab is-active"),
							Attr("data-pane", "preview"),
							html.Type("button"),
							Text("Preview"),
						),
						html.Button(
							html.Class("pg-tab"),
							Attr("data-pane", "go"),
							html.Type("button"),
							Text("Generated Go"),
						),
						html.Button(
							html.Class("pg-tab"),
							Attr("data-pane", "html"),
							html.Type("button"),
							Text("HTML"),
						),
					),
					html.Div(html.ID("pg-error"), html.Class("pg-error"), Attr("hidden")),
					html.Div(
						html.Class("pg-body"),
						Attr("data-pane-body", "preview"),
						El(
							"iframe",
							Attr("id", "pg-preview"),
							Attr("class", "pg-preview"),
							Attr("title", "Rendered output"),
							Attr("sandbox", ""),
						),
					),
					html.Div(
						html.Class("pg-body"),
						Attr("data-pane-body", "go"),
						Attr("hidden"),
						html.Pre(html.Class("pg-out"), html.Code(html.ID("pg-go"))),
					),
					html.Div(
						html.Class("pg-body"),
						Attr("data-pane-body", "html"),
						Attr("hidden"),
						html.Pre(html.Class("pg-out"), html.Code(html.ID("pg-html"))),
					),
				),
			),
			html.Div(
				html.Class("pg-note"),
				html.P(
					Text("Everything here runs in your browser. The compiler is the same one the"),
					Text(" "),
					html.Code(Text("gsx")),
					Text(
						" command uses, built to WebAssembly; the generated Go is interpreted rather than built, so no code leaves the page and there is no server to send it to.",
					),
				),
				html.P(
					html.Class("muted"),
					Text("The interpreter can see "),
					Text(" "),
					html.Code(Text("gomponents")),
					Text(", "),
					html.Code(Text("fmt")),
					Text(","),
					Text(" "),
					html.Code(Text("strings")),
					Text(", "),
					html.Code(Text("strconv")),
					Text(" and "),
					html.Code(Text("sort")),
					Text(". It cannot see "),
					html.Code(Text("os")),
					Text(" or "),
					html.Code(Text("net")),
					Text(
						" — those packages are simply absent, which is what makes running a stranger's snippet safe.",
					),
				),
				html.P(
					html.Class("muted"),
					Text("The editor is Monaco using the same TextMate grammar as the"),
					Text(" "),
					html.A(
						html.Href(
							"https://marketplace.visualstudio.com/items?itemName=kilianc.gsx-vscode",
						),
						Text("VS Code extension"),
					),
					Text(
						", so tags and Go highlight here exactly as they do there. Type checking, hover and go-to-definition are not available: those come from gopls, which needs a real toolchain and a filesystem. Install the extension for those.",
					),
				),
			),
		},
	}
}
