// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package localplay

import (
	"fmt"

	. "maragu.dev/gomponents"

	// ItemsList is a tiny helper so you can test go-to-definition/hover from a .gsx file.
	html "maragu.dev/gomponents/html"
)

func ItemsList(lis []Node) Node {
	return html.Ul(html.Class("items"), Group(lis))
}

func Page(title string, items []string, show bool) Node {
	if title == "" {
		return html.P(Text("no title"))
	}

	var lis []Node
	for _, it := range items {
		lis = append(lis, html.Li(html.Class("item"), Text(it)))
	}

	// Intentional error (to verify diagnostics from gopls show up in .gsx):
	// Uncomment this to see an "undefined: notDefined" error.
	// _ = notDefined

	banner := html.Div(
		html.Class("page"),
		html.H1(Text(title)),
		If(show, html.P(Text(fmt.Sprintf("items: %d", len(items))))),
		ItemsList(lis),
	)

	return banner
}
