// Command demogen renders the frames of the README demo animation.
//
// Everything on screen is real: the left pane is cmd/demogen/ui/cart.gsx
// verbatim, the right pane is what the compiler produces from it, and the strip
// along the bottom is the HTML that component actually renders. Nothing is
// mocked up, so a change to the compiler or the highlighter shows up in the next
// animation rather than quietly making the README a lie.
//
// It writes one HTML file per frame. Turning those into a GIF is `make
// demo-reel`, which screenshots them at twice their display size and encodes
// with gifski — see tools/demo.Dockerfile.
package main

import (
	_ "embed"
	"flag"
	"fmt"
	"html/template"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/kilianc/gsx/cmd/demogen/ui"
	"github.com/kilianc/gsx/internal/gsx/highlight"
	"github.com/kilianc/gsx/pkg/gsx"
)

//go:embed ui/cart.gsx
var source string

// frame is one rendered still: how much of each pane has been typed, and what
// the chrome around them is doing.
type frame struct {
	gsxRunes int
	goRunes  int
	caret    byte // 'g' in the source pane, 'o' in the generated pane, 0 for none
	pill     bool
	preview  bool
}

// demoItems are what the loop in the demo source runs over. Three is enough to
// show repetition, and one on sale exercises the branch inside it.
var demoItems = []ui.Item{
	{Name: "Keyboard"},
	{Name: "Monitor", Sale: true},
	{Name: "Desk mat"},
}

func main() {
	out := flag.String("out", "", "directory to write frame HTML into (required)")
	flag.Parse()
	if *out == "" {
		flag.Usage()
		os.Exit(2)
	}

	src := strings.TrimRight(source, "\n")

	// The generated pane is the compiler's own output for the file in the left
	// pane, minus the header a reader does not need to see typed out.
	compiled, err := gsx.CompileFile("cart.gsx", []byte(src+"\n"))
	if err != nil {
		log.Fatalf("demogen: compiling the demo source: %v", err)
	}
	gen := trimHeader(string(compiled))

	var page strings.Builder
	if err := ui.Cart(demoItems).Render(&page); err != nil {
		log.Fatalf("demogen: rendering the demo component: %v", err)
	}

	if err := os.MkdirAll(*out, 0o755); err != nil {
		log.Fatal(err)
	}
	frames := timeline([]rune(src), []rune(gen))
	for i, f := range frames {
		html, err := render(f, []rune(src), []rune(gen), page.String())
		if err != nil {
			log.Fatal(err)
		}
		name := filepath.Join(*out, fmt.Sprintf("%04d.html", i+1))
		if err := os.WriteFile(name, []byte(html), 0o644); err != nil {
			log.Fatal(err)
		}
	}
	fmt.Printf("demogen: wrote %d frames to %s\n", len(frames), *out)
}

// trimHeader drops the generated-code banner and the import block. The demo has
// room for the function, and the boilerplate is the least interesting part of
// what the compiler produces.
func trimHeader(s string) string {
	lines := strings.Split(s, "\n")
	keep := 0
	for i, l := range lines {
		if strings.TrimSpace(l) == ")" {
			keep = i + 1
			break
		}
	}
	body := strings.TrimSpace(strings.Join(lines[keep:], "\n"))
	return "// Code generated by gsxgo.\npackage ui\n\n" + body
}

// timeline lays out the animation: type the source, run the compiler, type what
// it produced, then show the page. The counts are frames at 20fps.
func timeline(src, gen []rune) []frame {
	var fs []frame
	add := func(n int, f frame) {
		for i := 0; i < n; i++ {
			fs = append(fs, f)
		}
	}

	add(4, frame{caret: 'g'})

	const typeSrc = 34
	for i := 1; i <= typeSrc; i++ {
		add(1, frame{gsxRunes: len(src) * i / typeSrc, caret: 'g'})
	}
	add(5, frame{gsxRunes: len(src), caret: 'g'})

	// The compiler runs: the pill appears before anything lands in the right
	// pane, which is the beat that says the Go is generated rather than written.
	add(5, frame{gsxRunes: len(src), pill: true})

	const typeGen = 30
	for i := 1; i <= typeGen; i++ {
		add(1, frame{gsxRunes: len(src), goRunes: len(gen) * i / typeGen, caret: 'o', pill: true})
	}
	add(4, frame{gsxRunes: len(src), goRunes: len(gen)})

	add(16, frame{gsxRunes: len(src), goRunes: len(gen), preview: true})
	return fs
}

type view struct {
	GSX     template.HTML
	Go      template.HTML
	Pill    bool
	Preview bool
	Page    template.HTML
}

func render(f frame, src, gen []rune, page string) (string, error) {
	v := view{
		GSX:     pane(src, f.gsxRunes, f.caret == 'g'),
		Go:      pane(gen, f.goRunes, f.caret == 'o'),
		Pill:    f.pill,
		Preview: f.preview,
		Page:    template.HTML(page),
	}
	var sb strings.Builder
	if err := tmpl.Execute(&sb, v); err != nil {
		return "", err
	}
	return sb.String(), nil
}

// pane highlights the first n runes and parks the caret at the end, so a
// half-typed line is coloured the way the editor would colour it.
func pane(text []rune, n int, caret bool) template.HTML {
	out := highlight.HTML(string(text[:n]))
	if caret {
		out += `<span class="caret"></span>`
	}
	return template.HTML(out)
}

// The window is 920 wide because that is the width the README displays, and
// tall enough for the loop to fit without scrolling. It is captured at twice
// that, which is the entire point of the exercise.
//
// The palette is the site's dark one: the site itself is light everywhere now,
// but a code window in a README is read as a screenshot of an editor, and every
// editor people take screenshots of is dark. The accent is Go's #00add8, the
// shade of Gopher Blue that belongs on a dark background.
var tmpl = template.Must(template.New("frame").Parse(`<!doctype html>
<meta charset="utf-8">
<style>
  :root {
    --accent: #00add8;
    --win: #131720;
    --chrome: #0f131b;
    --line: #222a38;
    --fg: #ececf0;
    --muted: #6f7b8f;
    --mono: "DejaVu Sans Mono", ui-monospace, SFMono-Regular, Menlo, monospace;
    --sans: "DejaVu Sans", -apple-system, "Segoe UI", Roboto, sans-serif;
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; }
  body { width: 920px; height: 430px; overflow: hidden; font-family: var(--sans); }

  .win { width: 920px; height: 430px; background: var(--win); display: flex; flex-direction: column; }

  .bar { height: 36px; flex: none; background: var(--chrome); display: flex; align-items: center; padding: 0 14px; position: relative; }
  .dot { width: 11px; height: 11px; border-radius: 50%; margin-right: 7px; }
  .dot-r { background: #ff5f57; } .dot-y { background: #febc2e; } .dot-g { background: #28c840; }
  .title { position: absolute; left: 0; right: 0; text-align: center; font-size: 12px; color: var(--muted); }

  .tabs { height: 34px; flex: none; display: flex; border-bottom: 1px solid var(--line); }
  .tab { padding: 0 18px; display: flex; align-items: center; gap: 7px; font-size: 12.5px; font-weight: 700; color: var(--fg); }
  /* The generated pane is wider: the same code with html. prefixes on it. */
  .tab-l { width: 430px; }
  .tab-r { width: 490px; }
  /* The underline marks the file, not the pane, so it sits on the label. */
  .tab .name { align-self: stretch; display: flex; align-items: center; }
  .tab.is-active .name { box-shadow: inset 0 -2px 0 var(--accent); }
  .tab .note { font-weight: 400; color: var(--muted); }

  .panes { flex: 1; display: flex; position: relative; min-height: 0; }
  /* The source is tab-indented; two columns is what the editor and the docs
     site both show, and eight would push the generated pane off its own edge. */
  .pane { width: 430px; margin: 0; padding: 14px 18px; font: 11.5px/17px var(--mono);
          color: var(--fg); white-space: pre; overflow: hidden; tab-size: 2; -moz-tab-size: 2; }
  .pane-r { width: 490px; border-left: 1px solid var(--line); }

  .caret { display: inline-block; width: 6px; height: 13px; background: var(--accent); vertical-align: -3px; }

  .pill { position: absolute; left: 50%; top: 46%; transform: translate(-50%, -50%);
          padding: 4px 12px; border: 1px solid var(--accent); border-radius: 999px;
          background: var(--win); color: var(--accent); font: 600 11px/1 var(--mono); white-space: nowrap; }

  .strip { height: 76px; flex: none; border-top: 1px solid var(--line); }
  .waiting { height: 100%; display: flex; align-items: center; padding: 0 18px; font-size: 12.5px; color: var(--muted); }
  .browser { height: 100%; background: #fbfbfa; padding: 8px 18px; }
  .url { font: 11px/1.6 var(--mono); color: #92929c; }
  .cart { display: flex; gap: 8px; list-style: none; margin: 8px 0 0; padding: 0; }
  .cart li { font-size: 13px; padding: 5px 12px; border-radius: 999px; background: #ececea; color: #1a1a1c; }
  /* The light shade of Gopher Blue: this strip is the rendered page, not chrome. */
  .cart .sale { background: #007d9c; color: #fff; font-weight: 600; }

  .hl-c  { color: #6f6f7b; font-style: italic; }
  .hl-s  { color: #6ee7a8; }
  .hl-n  { color: #f0b866; }
  .hl-k  { color: #e08ce8; }
  .hl-t  { color: #8ab4ff; }
  .hl-tg { color: #ff8f80; }
  .hl-at { color: #f0b866; }
  .hl-br { color: var(--accent); font-weight: 700; }
  .hl-p  { color: #75757f; }
</style>
<div class="win">
  <div class="bar">
    <span class="dot dot-r"></span><span class="dot dot-y"></span><span class="dot dot-g"></span>
    <span class="title">gsx dev &mdash; ~/shop</span>
  </div>
  <div class="tabs">
    <div class="tab tab-l is-active"><span class="name">cart.gsx</span></div>
    <div class="tab tab-r"><span class="name">cart.gsx.go</span> <span class="note">generated</span></div>
  </div>
  <div class="panes">
    <pre class="pane">{{.GSX}}</pre>
    <pre class="pane pane-r">{{.Go}}</pre>
    {{if .Pill}}<div class="pill">gsx ./...</div>{{end}}
  </div>
  <div class="strip">
    {{if .Preview}}
      <div class="browser">
        <div class="url">localhost:8080</div>
        {{.Page}}
      </div>
    {{else}}
      <div class="waiting">waiting for first render&hellip;</div>
    {{end}}
  </div>
</div>
`))
