package compile

import (
	"bytes"
	"fmt"
	goast "go/ast"
	"go/format"
	"go/parser"
	gotoken "go/token"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"

	"github.com/kilianc/gsx/internal/gsx/ast"
	"github.com/kilianc/gsx/internal/gsx/gomponents"
	"github.com/kilianc/gsx/internal/gsx/module"
)

const (
	SoftHeader        = "// Code generated by gsxgo. Edits may be overwritten on regen.\n"
	StaticcheckHeader = "//lint:file-ignore ST1001 dot imports are required in generated code\n"
)

const maxSingleLineCallLen = 80

type compileResult struct {
	fset        *gotoken.FileSet
	af          *goast.File
	mapping     []placeholder
	rewritten   []byte
	qualifyHTML bool
}

func compilePipeline(path string, src []byte) (*compileResult, error) {
	rewritten, mapping, err := rewriteTagsToPlaceholders(src)
	if err != nil {
		return nil, err
	}
	rewritten = normalizeParenWrappedPlaceholder(rewritten)

	fset := gotoken.NewFileSet()
	af, err := parser.ParseFile(fset, path+".go", rewritten, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("%w\n\n-- rewritten preview --\n%s", err, previewLines(string(rewritten), 80))
	}

	funcReturnTypes := resolveImportedFuncTypes(af)
	if funcReturnTypes == nil {
		funcReturnTypes = map[string]string{}
	}
	for name, typ := range collectLocalFuncReturnTypes(af) {
		funcReturnTypes[name] = typ
	}

	funcParams := resolveImportedFuncParams(af)
	if funcParams == nil {
		funcParams = map[string][]gomponents.FuncParam{}
	}
	for name, params := range collectLocalFuncParams(af) {
		funcParams[name] = params
	}

	qualifyHTML := hasUserDotImports(af)
	htmlPrefix := ""
	if qualifyHTML {
		htmlPrefix = "html"
	}

	ctx := gomponents.Context{
		VarTypes:        inferVarTypesFromPlaceholders(af, mapping, funcReturnTypes),
		FuncReturnTypes: funcReturnTypes,
		FuncParams:      funcParams,
		HTMLPrefix:      htmlPrefix,
	}

	for i := range mapping {
		ex, err := gomponents.LowerNodes([]ast.Node{mapping[i].node}, ctx)
		if err != nil {
			return nil, err
		}
		clearTokenPos(ex)
		mapping[i].expr = ex
	}

	return &compileResult{fset: fset, af: af, mapping: mapping, rewritten: rewritten, qualifyHTML: qualifyHTML}, nil
}

// CompileFile compiles a Go-first .gsx source (a Go file with embedded `<tag>` expressions)
// into a gofmt'd Go source file.
func CompileFile(path string, src []byte) ([]byte, error) {
	cr, err := compilePipeline(path, src)
	if err != nil {
		return nil, err
	}

	ensureImports(cr.af, cr.mapping, cr.qualifyHTML)

	var buf bytes.Buffer
	if err := format.Node(&buf, cr.fset, cr.af); err != nil {
		return nil, err
	}

	gofmted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, err
	}

	pretty, err := substitutePlaceholdersWithPrettyExprs(string(gofmted), cr.mapping, maxSingleLineCallLen)
	if err != nil {
		return nil, err
	}

	out := append([]byte(nil), []byte(SoftHeader)...)
	out = append(out, []byte(strings.TrimRight(StaticcheckHeader, "\n"))...)
	out = append(out, '\n', '\n')
	out = append(out, []byte(formatImportGroups(pretty))...)
	final, err := format.Source(out)
	if err != nil {
		return nil, fmt.Errorf("gofmt final: %w\n\n-- output preview --\n%s", err, previewLines(string(out), 120))
	}
	return final, nil
}

// CompileFileForLSP compiles a .gsx source into a Go source file suitable for feeding to gopls.
//
// Unlike CompileFile, it does NOT inline tag expressions at call sites. Instead, tag expressions are
// replaced with stable placeholder calls like `__gsx_expr_1()` and the corresponding helper functions
// are appended to the file.
//
// It also returns the rewritten Go-ish source (tags -> placeholders) to help higher layers build
// best-effort mappings back to the original .gsx file.
func CompileFileForLSP(path string, src []byte) (goSrc []byte, sm *SourceMap, err error) {
	cr, err := compilePipeline(path, src)
	if err != nil {
		return nil, nil, err
	}

	rewritten := string(cr.rewritten)
	mapping := cr.mapping

	// normalizeParenWrappedPlaceholder may remove lines and change the positions of placeholder calls.
	// Re-index placeholder target positions so we can safely apply inline expansions.
	if mapping, err = reindexPlaceholderTargets(rewritten, mapping); err != nil {
		return nil, nil, err
	}

	loweredExprs := map[string]string{}
	for i := range mapping {
		loweredExprs[mapping[i].name] = formatExpr(mapping[i].expr)
	}

	// Apply minimal import edits and inline placeholder expansions to produce a gopls-friendly Go view.
	req := detectRequiredImports(mapping, mapsToSlice(loweredExprs))
	req.qualifyHTML = cr.qualifyHTML
	impRes := applyImportEdits(rewritten, req)

	// When we changed imports, all subsequent placeholder offsets shift.
	afterImports := impRes.out
	adjusted := make([]placeholder, len(mapping))
	for i := range mapping {
		p := mapping[i]
		ns, _ := impRes.mp.tgtOffsetFromSrcOffset(p.tgtStart)
		ne, _ := impRes.mp.tgtOffsetFromSrcOffset(p.tgtEnd)
		p.tgtStart = ns
		p.tgtEnd = ne
		adjusted[i] = p
	}

	expRes := applyInlineExpansions(afterImports, adjusted, loweredExprs, true, true)
	goView := expRes.out

	// Build source map: src(.gsx) -> rewritten(placeholders) -> afterImports -> goView.
	srcStr := string(src)
	srcToRew, rewToSrc := buildRewriteMappers(srcStr, mapping)

	sm = &SourceMap{
		src:                     newLineIndex(srcStr),
		tgt:                     newLineIndex(goView),
		srcToRewritten:          srcToRew,
		rewrittenToSrc:          rewToSrc,
		rewrittenToAfterImports: impRes.mp,
		afterImportsToRewritten: impRes.mp,
		afterImportsToTgt:       expRes.mp,
		tgtToAfterImports:       expRes.mp,
	}

	return []byte(goView), sm, nil
}

func reindexPlaceholderTargets(rewritten string, phs []placeholder) ([]placeholder, error) {
	// Each placeholder name is unique, so we can locate `name()` exactly once.
	// We scan left-to-right to keep it linear and robust.
	out := make([]placeholder, len(phs))
	searchFrom := 0
	for i := range phs {
		needle := phs[i].name + "()"
		j := strings.Index(rewritten[searchFrom:], needle)
		if j < 0 {
			return nil, fmt.Errorf("lsp: could not locate placeholder %q in rewritten source", needle)
		}
		j += searchFrom
		p := phs[i]
		p.tgtStart = j
		p.tgtEnd = j + len(needle)
		out[i] = p
		searchFrom = p.tgtEnd
	}
	return out, nil
}

func mapsToSlice(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for _, v := range m {
		out = append(out, v)
	}
	return out
}

func resolveImportedFuncTypes(f *goast.File) map[string]string {
	modPath, modRoot := module.FindModuleInfo()
	if modPath == "" {
		return nil
	}
	result := map[string]string{}
	for _, spec := range f.Imports {
		importPath := strings.Trim(spec.Path.Value, `"`)
		if !strings.HasPrefix(importPath, modPath+"/") && importPath != modPath {
			continue
		}
		relDir := strings.TrimPrefix(importPath, modPath)
		relDir = strings.TrimPrefix(relDir, "/")
		absDir := filepath.Join(modRoot, relDir)

		isDotImport := spec.Name != nil && spec.Name.Name == "."
		localName := filepath.Base(importPath)
		if spec.Name != nil && spec.Name.Name != "." && spec.Name.Name != "_" {
			localName = spec.Name.Name
		}

		funcTypes := parseFuncReturnTypesFromDir(absDir)
		for funcName, retType := range funcTypes {
			if isDotImport {
				result[funcName] = retType
			} else {
				result[localName+"."+funcName] = retType
			}
		}
	}
	return result
}


func parseFuncReturnTypesFromDir(dir string) map[string]string {
	fset := gotoken.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, 0)
	if err != nil {
		return nil
	}
	result := map[string]string{}
	for _, pkg := range pkgs {
		if strings.HasSuffix(pkg.Name, "_test") {
			continue
		}
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				fd, ok := decl.(*goast.FuncDecl)
				if !ok || fd.Recv != nil {
					continue
				}
				if !fd.Name.IsExported() {
					continue
				}
				if fd.Type.Results == nil || fd.Type.Results.NumFields() != 1 {
					continue
				}
				retType := classifyASTReturnType(fd.Type.Results.List[0].Type, file.Imports)
				if retType != "" {
					result[fd.Name.Name] = retType
				}
			}
		}
	}
	return result
}

func classifyASTReturnType(expr goast.Expr, imports []*goast.ImportSpec) string {
	switch t := expr.(type) {
	case *goast.Ident:
		if t.Name == "string" {
			return "string"
		}
		if t.Name == "Node" {
			return "Node"
		}
	case *goast.SelectorExpr:
		if t.Sel.Name == "Node" {
			if xID, ok := t.X.(*goast.Ident); ok {
				for _, imp := range imports {
					impPath := strings.Trim(imp.Path.Value, `"`)
					localName := filepath.Base(impPath)
					if imp.Name != nil {
						localName = imp.Name.Name
					}
					if localName == xID.Name && strings.Contains(impPath, "gomponents") {
						return "Node"
					}
				}
			}
		}
	}
	return ""
}

func collectLocalFuncReturnTypes(f *goast.File) map[string]string {
	result := map[string]string{}
	for _, decl := range f.Decls {
		fd, ok := decl.(*goast.FuncDecl)
		if !ok || fd.Recv != nil {
			continue
		}
		if fd.Type.Results == nil || fd.Type.Results.NumFields() != 1 {
			continue
		}
		retType := classifyASTReturnType(fd.Type.Results.List[0].Type, f.Imports)
		if retType != "" {
			result[fd.Name.Name] = retType
		}
	}
	return result
}

func resolveImportedFuncParams(f *goast.File) map[string][]gomponents.FuncParam {
	modPath, modRoot := module.FindModuleInfo()
	if modPath == "" {
		return nil
	}
	result := map[string][]gomponents.FuncParam{}
	for _, spec := range f.Imports {
		importPath := strings.Trim(spec.Path.Value, `"`)
		if !strings.HasPrefix(importPath, modPath+"/") && importPath != modPath {
			continue
		}
		relDir := strings.TrimPrefix(importPath, modPath)
		relDir = strings.TrimPrefix(relDir, "/")
		absDir := filepath.Join(modRoot, relDir)

		isDotImport := spec.Name != nil && spec.Name.Name == "."
		localName := filepath.Base(importPath)
		if spec.Name != nil && spec.Name.Name != "." && spec.Name.Name != "_" {
			localName = spec.Name.Name
		}

		funcParams := parseFuncParamsFromDir(absDir)
		for funcName, params := range funcParams {
			if isDotImport {
				result[funcName] = params
			} else {
				result[localName+"."+funcName] = params
			}
		}
	}
	return result
}

func parseFuncParamsFromDir(dir string) map[string][]gomponents.FuncParam {
	fset := gotoken.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, 0)
	if err != nil {
		return nil
	}
	result := map[string][]gomponents.FuncParam{}
	for _, pkg := range pkgs {
		if strings.HasSuffix(pkg.Name, "_test") {
			continue
		}
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				fd, ok := decl.(*goast.FuncDecl)
				if !ok || fd.Recv != nil {
					continue
				}
				if !fd.Name.IsExported() {
					continue
				}
				if fd.Type.Results == nil || fd.Type.Results.NumFields() != 1 {
					continue
				}
				retType := classifyASTReturnType(fd.Type.Results.List[0].Type, file.Imports)
				if retType != "Node" {
					continue
				}
				params := extractFuncParams(fd.Type.Params, file.Imports)
				if params != nil {
					result[fd.Name.Name] = params
				}
			}
		}
	}
	return result
}

func collectLocalFuncParams(f *goast.File) map[string][]gomponents.FuncParam {
	result := map[string][]gomponents.FuncParam{}
	for _, decl := range f.Decls {
		fd, ok := decl.(*goast.FuncDecl)
		if !ok || fd.Recv != nil {
			continue
		}
		if fd.Type.Results == nil || fd.Type.Results.NumFields() != 1 {
			continue
		}
		retType := classifyASTReturnType(fd.Type.Results.List[0].Type, f.Imports)
		if retType != "Node" {
			continue
		}
		params := extractFuncParams(fd.Type.Params, f.Imports)
		if params != nil {
			result[fd.Name.Name] = params
		}
	}
	return result
}

func extractFuncParams(fl *goast.FieldList, imports []*goast.ImportSpec) []gomponents.FuncParam {
	if fl == nil || fl.NumFields() == 0 {
		return nil
	}
	var params []gomponents.FuncParam
	for _, field := range fl.List {
		isVariadic := false
		typeExpr := field.Type
		if ell, ok := field.Type.(*goast.Ellipsis); ok {
			isVariadic = true
			typeExpr = ell.Elt
		}
		typeName := classifyParamType(typeExpr, imports)
		if typeName == "" {
			return nil
		}
		if len(field.Names) == 0 {
			params = append(params, gomponents.FuncParam{
				Type:     typeName,
				Variadic: isVariadic,
			})
		} else {
			for _, name := range field.Names {
				params = append(params, gomponents.FuncParam{
					Name:     name.Name,
					Type:     typeName,
					Variadic: isVariadic,
				})
			}
		}
	}
	return params
}

func classifyParamType(expr goast.Expr, imports []*goast.ImportSpec) string {
	switch t := expr.(type) {
	case *goast.Ident:
		switch t.Name {
		case "string", "bool", "int", "int64", "float64", "Node":
			return t.Name
		}
	case *goast.SelectorExpr:
		if t.Sel.Name == "Node" {
			if xID, ok := t.X.(*goast.Ident); ok {
				for _, imp := range imports {
					impPath := strings.Trim(imp.Path.Value, `"`)
					localName := filepath.Base(impPath)
					if imp.Name != nil {
						localName = imp.Name.Name
					}
					if localName == xID.Name && strings.Contains(impPath, "gomponents") {
						return "Node"
					}
				}
			}
		}
	}
	return ""
}

func resolveSelectorCallType(e goast.Expr, funcReturnTypes map[string]string) string {
	ce, ok := e.(*goast.CallExpr)
	if !ok {
		return ""
	}
	sel, ok := ce.Fun.(*goast.SelectorExpr)
	if !ok {
		return ""
	}
	xID, ok := sel.X.(*goast.Ident)
	if !ok {
		return ""
	}
	if typ, ok := funcReturnTypes[xID.Name+"."+sel.Sel.Name]; ok {
		return typ
	}
	return ""
}

func inferRHSType(rhs goast.Expr, phNames map[string]bool, funcReturnTypes map[string]string) string {
	ce, isCall := rhs.(*goast.CallExpr)
	if isCall {
		if id, ok := ce.Fun.(*goast.Ident); ok {
			if phNames[id.Name] && len(ce.Args) == 0 {
				return "Node"
			}
			if typ, ok := funcReturnTypes[id.Name]; ok {
				return typ
			}
		}
	}
	if resolved := resolveSelectorCallType(rhs, funcReturnTypes); resolved != "" {
		return resolved
	}
	if gomponents.IsExprStringish(rhs) {
		return "string"
	}
	if gomponents.IsLikelyNodeExpr(rhs, gomponents.Context{FuncReturnTypes: funcReturnTypes}) {
		return "Node"
	}
	return ""
}

func inferVarTypesFromPlaceholders(f *goast.File, phs []placeholder, funcReturnTypes map[string]string) map[string]string {
	phNames := map[string]bool{}
	for _, p := range phs {
		phNames[p.name] = true
	}

	structFields := collectStructFields(f)

	out := map[string]string{}
	goast.Inspect(f, func(n goast.Node) bool {
		switch t := n.(type) {
		case *goast.FuncDecl:
			if t.Type != nil && t.Type.Params != nil {
				for _, field := range t.Type.Params.List {
					typName := identName(field.Type)
					// Variadic params (...Node) are []Node inside the body.
					if typName == "" {
						if ell, ok := field.Type.(*goast.Ellipsis); ok {
							if id, ok := ell.Elt.(*goast.Ident); ok && id.Name == "Node" {
								typName = "[]Node"
							}
						}
					}
					if typName == "" {
						continue
					}
					for _, name := range field.Names {
						out[name.Name] = typName
						if fields, ok := structFields[typName]; ok {
							for fieldName, fieldType := range fields {
								out[name.Name+"."+fieldName] = fieldType
							}
						}
					}
				}
			}
		case *goast.AssignStmt:
			for i := range t.Rhs {
				if i < len(t.Lhs) {
					if lhsID, ok := t.Lhs[i].(*goast.Ident); ok {
						if typ := inferRHSType(t.Rhs[i], phNames, funcReturnTypes); typ != "" {
							out[lhsID.Name] = typ
						}
					}
				}
			}
		case *goast.ValueSpec:
			if t.Type != nil {
				if typ := typeString(t.Type); typ != "" {
					for _, nm := range t.Names {
						out[nm.Name] = typ
					}
				}
			}
			for i := range t.Values {
				if i < len(t.Names) {
					if typ := inferRHSType(t.Values[i], phNames, funcReturnTypes); typ != "" {
						out[t.Names[i].Name] = typ
					}
				}
			}
		}
		return true
	})
	return out
}

func typeString(t goast.Expr) string {
	switch tt := t.(type) {
	case *goast.Ident:
		switch tt.Name {
		case "Node":
			return "Node"
		case "Group":
			// Group implements Node, but for our purposes "Node" is enough.
			return "Node"
		case "string":
			return "string"
		}
	case *goast.ArrayType:
		if tt.Len == nil {
			if id, ok := tt.Elt.(*goast.Ident); ok {
				if id.Name == "Node" {
					return "[]Node"
				}
				if id.Name == "string" {
					return "[]string"
				}
			}
		}
	}
	return ""
}

func collectStructFields(f *goast.File) map[string]map[string]string {
	out := map[string]map[string]string{}
	for _, decl := range f.Decls {
		gd, ok := decl.(*goast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*goast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*goast.StructType)
			if !ok {
				continue
			}
			fields := map[string]string{}
			for _, f := range st.Fields.List {
				typ := typeString(f.Type)
				if typ == "" {
					if sel, ok := f.Type.(*goast.SelectorExpr); ok && sel.Sel.Name == "Node" {
						typ = "Node"
					}
				}
				if typ == "" {
					continue
				}
				for _, name := range f.Names {
					fields[name.Name] = typ
				}
			}
			if len(fields) > 0 {
				out[ts.Name.Name] = fields
			}
		}
	}
	return out
}

func identName(t goast.Expr) string {
	if id, ok := t.(*goast.Ident); ok {
		return id.Name
	}
	return ""
}


func normalizeParenWrappedPlaceholder(src []byte) []byte {
	// The Go parser doesn't accept some "paren-wrapped expression" forms the way people expect,
	// e.g.:
	//   return (
	//     <div>...</div>
	//   )
	//   top := (
	//     <div>...</div>
	//   )
	//
	// After tag rewriting this becomes `__gsx_expr_N()`. We normalize the specific
	// 3-line pattern:
	//   <stmt-prefix> (
	//     __gsx_expr_N()
	//   )
	// to:
	//   <stmt-prefix> __gsx_expr_N()
	//
	// This keeps `.gsx` ergonomic without requiring us to fully parse Go here.
	lines := strings.Split(string(src), "\n")
	var out []string

	i := 0
	for i < len(lines) {
		line := lines[i]
		trim := strings.TrimSpace(line)

		if strings.HasSuffix(trim, "(") {
			// keep the original leading whitespace indentation
			indent := line[:len(line)-len(strings.TrimLeft(line, " \t"))]
			prefix := strings.TrimSpace(strings.TrimSuffix(trim, "("))

			// expect next line: placeholder call and then a close paren line
			if i+2 < len(lines) {
				exprLine := strings.TrimSpace(lines[i+1])
				closeLine := strings.TrimSpace(lines[i+2])
				if strings.HasPrefix(exprLine, "__gsx_expr_") && strings.HasSuffix(exprLine, "()") && strings.HasPrefix(closeLine, ")") {
					rest := closeLine[1:]
					out = append(out, indent+prefix+" "+exprLine+rest)
					i += 3
					continue
				}
			}
		}
		out = append(out, line)
		i++
	}
	return []byte(strings.Join(out, "\n"))
}

func previewLines(s string, max int) string {
	lines := strings.Split(s, "\n")
	if len(lines) > max {
		lines = lines[:max]
	}
	for i := range lines {
		lines[i] = fmt.Sprintf("%2d| %s", i+1, lines[i])
	}
	return strings.Join(lines, "\n")
}

type placeholder struct {
	name string
	node ast.Node
	expr goast.Expr
	// srcStart/srcEnd are byte offsets in the original .gsx source that were replaced by this placeholder call.
	srcStart int
	srcEnd   int
	// tgtStart/tgtEnd are byte offsets in the rewritten source (tags -> placeholder calls) that correspond to the placeholder call.
	tgtStart int
	tgtEnd   int
}

func rewriteTagsToPlaceholders(src []byte) ([]byte, []placeholder, error) {
	s := &scanner{src: src}
	var out strings.Builder
	var phs []placeholder

	for !s.eof() {
		if s.startsWith("//") {
			out.WriteString(s.readLineComment())
			continue
		}
		if s.startsWith("/*") {
			out.WriteString(s.readBlockComment())
			continue
		}
		switch s.peek() {
		case '"':
			out.WriteString(s.readStringLit())
			continue
		case '\'':
			out.WriteString(s.readRuneLit())
			continue
		case '`':
			out.WriteString(s.readRawString())
			continue
		case '<':
			// Disambiguate: treat as tag only if next char is an identifier start.
			if b := s.peekN(1); isTagStart(b) {
				srcStart := s.i
				el, err := parseTagExpr(s)
				if err != nil {
					return nil, nil, err
				}
				srcEnd := s.i
				name := "__gsx_expr_" + strconv.Itoa(len(phs)+1)
				tgtStart := out.Len()
				out.WriteString(name)
				out.WriteString("()")
				tgtEnd := out.Len()
				phs = append(phs, placeholder{
					name:     name,
					node:     el,
					srcStart: srcStart,
					srcEnd:   srcEnd,
					tgtStart: tgtStart,
					tgtEnd:   tgtEnd,
				})
				continue
			}
		}
		out.WriteByte(s.next())
	}
	return []byte(out.String()), phs, nil
}

func ensureImports(f *goast.File, phs []placeholder, qualifyHTML bool) {
	// We always need dot imports for gomponents + html when any tags exist.
	needsTags := len(phs) > 0

	needsFmt := usesPkgSelector(f, "fmt")
	needsComponents := usesIdent(f, "JoinAttrs") || usesIdent(f, "Classes")
	for _, p := range phs {
		if !needsFmt && usesPkgSelector(p.expr, "fmt") {
			needsFmt = true
		}
		if !needsComponents && (usesIdent(p.expr, "JoinAttrs") || usesIdent(p.expr, "Classes")) {
			needsComponents = true
		}
	}

	// Drop any existing imports of these paths; we'll re-add with dot import as needed.
	drop := map[string]bool{
		"maragu.dev/gomponents":            true,
		"maragu.dev/gomponents/html":       true,
		"maragu.dev/gomponents/components": true,
	}

	var keep []*goast.ImportSpec
	existing := map[string]*goast.ImportSpec{}
	for _, imp := range f.Imports {
		p := strings.Trim(imp.Path.Value, `"`)
		if drop[p] {
			continue
		}
		existing[p] = imp
		keep = append(keep, imp)
	}

	var add []impSpec
	if needsTags {
		add = append(add, impSpec{name: ".", path: "maragu.dev/gomponents"})
		if qualifyHTML {
			add = append(add, impSpec{name: "html", path: "maragu.dev/gomponents/html"})
		} else {
			add = append(add, impSpec{name: ".", path: "maragu.dev/gomponents/html"})
		}
	}
	if needsComponents {
		add = append(add, impSpec{name: ".", path: "maragu.dev/gomponents/components"})
	}
	if needsFmt {
		add = append(add, impSpec{name: "", path: "fmt"})
	}

	// Build final import list, de-duping by path+name.
	type key struct{ name, path string }
	seen := map[key]bool{}
	var specs []*goast.ImportSpec

	for _, imp := range keep {
		k := key{name: "", path: strings.Trim(imp.Path.Value, `"`)}
		if imp.Name != nil {
			k.name = imp.Name.Name
		}
		if !seen[k] {
			seen[k] = true
			specs = append(specs, imp)
		}
	}
	for _, a := range add {
		k := key{name: a.name, path: a.path}
		if seen[k] {
			continue
		}
		seen[k] = true
		var nameIdent *goast.Ident
		if a.name != "" {
			nameIdent = goast.NewIdent(a.name)
		}
		specs = append(specs, &goast.ImportSpec{
			Name: nameIdent,
			Path: &goast.BasicLit{Kind: gotoken.STRING, Value: strconv.Quote(a.path)},
		})
	}

	if len(specs) == 0 {
		return
	}

	// Sort imports by path then name for determinism.
	sort.Slice(specs, func(i, j int) bool {
		pi := strings.Trim(specs[i].Path.Value, `"`)
		pj := strings.Trim(specs[j].Path.Value, `"`)
		if pi != pj {
			return pi < pj
		}
		ni := ""
		nj := ""
		if specs[i].Name != nil {
			ni = specs[i].Name.Name
		}
		if specs[j].Name != nil {
			nj = specs[j].Name.Name
		}
		return ni < nj
	})

	// For parenthesized imports, modify the existing decl in place to preserve
	// its position info, which prevents go/format from displacing nearby comments.
	var parenImport *goast.GenDecl
	var newDecls []goast.Decl
	for _, d := range f.Decls {
		gd, ok := d.(*goast.GenDecl)
		if ok && gd.Tok == gotoken.IMPORT {
			if parenImport == nil && gd.Lparen.IsValid() {
				parenImport = gd
				newDecls = append(newDecls, d)
			}
			continue
		}
		newDecls = append(newDecls, d)
	}
	f.Decls = newDecls
	f.Imports = specs

	if parenImport != nil {
		parenImport.Specs = nil
		for _, s := range specs {
			parenImport.Specs = append(parenImport.Specs, s)
		}
	} else {
		impDecl := &goast.GenDecl{Tok: gotoken.IMPORT}
		for _, s := range specs {
			impDecl.Specs = append(impDecl.Specs, s)
		}
		f.Decls = append([]goast.Decl{impDecl}, f.Decls...)
	}
}

func usesPkgSelector(node goast.Node, pkg string) bool {
	found := false
	goast.Inspect(node, func(n goast.Node) bool {
		if found || n == nil {
			return false
		}
		if sel, ok := n.(*goast.SelectorExpr); ok {
			if id, ok := sel.X.(*goast.Ident); ok && id.Name == pkg {
				found = true
				return false
			}
		}
		return true
	})
	return found
}

func usesIdent(node goast.Node, name string) bool {
	found := false
	goast.Inspect(node, func(n goast.Node) bool {
		if found || n == nil {
			return false
		}
		if id, ok := n.(*goast.Ident); ok && id.Name == name {
			found = true
			return false
		}
		return true
	})
	return found
}

func hasUserDotImports(f *goast.File) bool {
	for _, spec := range f.Imports {
		if spec.Name != nil && spec.Name.Name == "." {
			path := strings.Trim(spec.Path.Value, `"`)
			if !strings.HasPrefix(path, "maragu.dev/gomponents") {
				return true
			}
		}
	}
	return false
}

type impSpec struct {
	name string
	path string
}

func substitutePlaceholdersWithPrettyExprs(src string, phs []placeholder, maxLen int) (string, error) {
	out := src
	for _, p := range phs {
		pretty := prettyExpr(p.expr, maxLen, 0)
		out = replaceAllWithIndent(out, p.name+"()", pretty)
	}
	return out, nil
}

func replaceAllWithIndent(src, needle, replacement string) string {
	if !strings.Contains(src, needle) {
		return src
	}

	var b strings.Builder
	i := 0
	for {
		j := strings.Index(src[i:], needle)
		if j < 0 {
			b.WriteString(src[i:])
			break
		}
		j += i

		// Determine indentation prefix for this occurrence.
		lineStart := strings.LastIndexByte(src[:j], '\n')
		prefix := ""
		if lineStart >= 0 {
			k := lineStart + 1
			for k < len(src) && (src[k] == '\t' || src[k] == ' ') {
				k++
			}
			prefix = src[lineStart+1 : k]
		}

		b.WriteString(src[i:j])
		b.WriteString(applyIndent(prefix, replacement))
		i = j + len(needle)
	}
	return b.String()
}

func applyIndent(prefix, s string) string {
	if !strings.Contains(s, "\n") {
		return s
	}
	lines := strings.Split(s, "\n")
	for i := 1; i < len(lines); i++ {
		lines[i] = prefix + lines[i]
	}
	return strings.Join(lines, "\n")
}

func prettyExpr(e goast.Expr, maxLen int, depth int) string {
	switch t := e.(type) {
	case *goast.CallExpr:
		return prettyCall(t, maxLen, depth)
	default:
		return oneLineGoExpr(e)
	}
}

func prettyCall(c *goast.CallExpr, maxLen int, depth int) string {
	fun := oneLineGoExpr(c.Fun)

	// Build one-line candidate.
	var argOnes []string
	hasMulti := false
	for _, a := range c.Args {
		as := prettyExpr(a, maxLen, depth+1)
		if strings.Contains(as, "\n") {
			hasMulti = true
		}
		argOnes = append(argOnes, oneLineFromMaybeMulti(as))
	}
	one := fun + "(" + strings.Join(argOnes, ", ") + ")"
	if !hasMulti && len(one) <= maxLen {
		return one
	}

	// Multiline: one arg per line.
	var b strings.Builder
	b.WriteString(fun)
	b.WriteString("(\n")
	for _, a := range c.Args {
		as := prettyExpr(a, maxLen, depth+1)
		as = indentLines(as, "\t")
		b.WriteString(as)
		b.WriteString(",\n")
	}
	b.WriteString(")")
	return b.String()
}

func oneLineGoExpr(e goast.Expr) string {
	fset := gotoken.NewFileSet()
	var buf bytes.Buffer
	_ = format.Node(&buf, fset, e)
	return strings.Join(strings.Fields(strings.TrimSpace(buf.String())), " ")
}

func oneLineFromMaybeMulti(s string) string {
	return strings.Join(strings.Fields(strings.TrimSpace(s)), " ")
}

func indentLines(s, indent string) string {
	lines := strings.Split(s, "\n")
	for i := range lines {
		lines[i] = indent + lines[i]
	}
	return strings.Join(lines, "\n")
}

func formatImportGroups(src string) string {
	// Ensure a blank line between stdlib imports and non-stdlib imports.
	// We only handle the common gofmt form:
	//   import (
	//       "fmt"
	//       . "maragu.dev/gomponents"
	//   )
	lines := strings.Split(src, "\n")
	inImport := false
	var out []string
	seenNonStd := false
	insertedGap := false

	for _, line := range lines {
		trim := strings.TrimSpace(line)
		if strings.HasPrefix(trim, "import") && strings.HasSuffix(trim, "(") {
			inImport = true
			seenNonStd = false
			insertedGap = false
			out = append(out, line)
			continue
		}
		if inImport && trim == ")" {
			inImport = false
			out = append(out, line)
			continue
		}
		if inImport {
			// import spec line: maybe starts with . or _ or identifier; find the quoted path.
			q := strings.Index(line, "\"")
			if q >= 0 {
				qq := strings.Index(line[q+1:], "\"")
				if qq >= 0 {
					path := line[q+1 : q+1+qq]
					isStd := isStdImportPath(path)
					if !isStd {
						if !seenNonStd {
							seenNonStd = true
						}
					} else if seenNonStd {
						// std after non-std shouldn't happen with our sorter; ignore
					}
					// Insert gap at boundary: first non-std after last std.
					if !insertedGap && !isStd {
						// If previous output line is a std import (not blank and within import),
						// insert a blank line before this non-std import.
						if len(out) > 0 {
							prev := strings.TrimSpace(out[len(out)-1])
							if prev != "" && prev != "(" && prev != "import (" {
								out = append(out, "")
								insertedGap = true
							}
						}
					}
				}
			}
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func isStdImportPath(path string) bool {
	// Heuristic: stdlib imports never have a '.' in the first path segment.
	seg := path
	if i := strings.IndexByte(seg, '/'); i >= 0 {
		seg = seg[:i]
	}
	return !strings.Contains(seg, ".")
}


// --- scanner + GSX tag parsing (subset of previous GSX v0) ---

type scanner struct {
	src []byte
	i   int
}

func (s *scanner) eof() bool { return s.i >= len(s.src) }
func (s *scanner) peek() byte {
	if s.eof() {
		return 0
	}
	return s.src[s.i]
}
func (s *scanner) peekN(n int) byte {
	j := s.i + n
	if j >= len(s.src) {
		return 0
	}
	return s.src[j]
}
func (s *scanner) next() byte {
	if s.eof() {
		return 0
	}
	b := s.src[s.i]
	s.i++
	return b
}
func (s *scanner) startsWith(prefix string) bool {
	return bytes.HasPrefix(s.src[s.i:], []byte(prefix))
}
func (s *scanner) readLineComment() string {
	start := s.i
	for !s.eof() && s.next() != '\n' {
	}
	return string(s.src[start:s.i])
}
func (s *scanner) readBlockComment() string {
	start := s.i
	s.next()
	s.next()
	for !s.eof() && !s.startsWith("*/") {
		s.next()
	}
	if s.startsWith("*/") {
		s.next()
		s.next()
	}
	return string(s.src[start:s.i])
}
func (s *scanner) readStringLit() string {
	start := s.i
	s.next()
	for !s.eof() {
		c := s.next()
		if c == '\\' {
			_ = s.next()
			continue
		}
		if c == '"' {
			break
		}
	}
	return string(s.src[start:s.i])
}
func (s *scanner) readRuneLit() string {
	start := s.i
	s.next()
	for !s.eof() {
		c := s.next()
		if c == '\\' {
			_ = s.next()
			continue
		}
		if c == '\'' {
			break
		}
	}
	return string(s.src[start:s.i])
}
func (s *scanner) readRawString() string {
	start := s.i
	s.next()
	for !s.eof() && s.next() != '`' {
	}
	return string(s.src[start:s.i])
}

func isTagStart(b byte) bool {
	return (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z')
}

func parseTagExpr(s *scanner) (ast.Node, error) {
	// assumes current is '<' and next is tag start
	if s.next() != '<' {
		return nil, fmt.Errorf("internal: expected <")
	}
	tagStart := s.i
	for {
		b := s.peek()
		if (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z') || (b >= '0' && b <= '9') || b == '-' || b == '.' {
			s.next()
			continue
		}
		break
	}
	tag := string(s.src[tagStart:s.i])

	var attrs []ast.Attr
	for {
		skipSpace(s)
		if s.startsWith("/>") {
			s.next()
			s.next()
			return ast.Element{Tag: tag, Attrs: attrs, SelfClosing: true}, nil
		}
		if s.peek() == '>' {
			s.next()
			break
		}
		// attribute injection: {expr}
		if s.peek() == '{' {
			expr, err := readBracedSource(s)
			if err != nil {
				return nil, err
			}
			expr, err = rewriteTagsInGoExpr(expr)
			if err != nil {
				return nil, err
			}
			attrs = append(attrs, ast.Attr{Key: "", Kind: ast.AttrExpr, Value: strings.TrimSpace(expr)})
			continue
		}
		attr, err := parseAttr(s)
		if err != nil {
			return nil, err
		}
		attrs = append(attrs, attr)
	}

	// children until </tag>
	var kids []ast.Node
	for {
		if s.eof() {
			return nil, fmt.Errorf("unexpected EOF in <%s>", tag)
		}
		if s.startsWith("</") {
			s.next()
			s.next()
			closeStart := s.i
			for (s.peek() >= 'a' && s.peek() <= 'z') || (s.peek() >= 'A' && s.peek() <= 'Z') || (s.peek() >= '0' && s.peek() <= '9') || s.peek() == '-' || s.peek() == '.' {
				s.next()
			}
			closeTag := string(s.src[closeStart:s.i])
			skipSpace(s)
			if s.peek() != '>' {
				return nil, fmt.Errorf("expected > for </%s>", closeTag)
			}
			s.next()
			if closeTag != tag {
				return nil, fmt.Errorf("mismatched closing tag </%s> for <%s>", closeTag, tag)
			}
			break
		}
		if s.peek() == '<' && isTagStart(s.peekN(1)) {
			n, err := parseTagExpr(s)
			if err != nil {
				return nil, err
			}
			kids = append(kids, n)
			continue
		}
		if s.peek() == '{' {
			expr, err := readBracedSource(s)
			if err != nil {
				return nil, err
			}
			expr, err = rewriteTagsInGoExpr(expr)
			if err != nil {
				return nil, err
			}
			kids = append(kids, ast.Expr{Src: strings.TrimSpace(expr)})
			continue
		}
		// text
		txtStart := s.i
		for !s.eof() {
			b := s.peek()
			if b == '<' || b == '{' {
				break
			}
			s.next()
		}
		if txtStart < s.i {
			v := string(s.src[txtStart:s.i])
			if strings.TrimSpace(v) != "" {
				kids = append(kids, ast.Text{Value: v})
			}
		}
	}

	return ast.Element{Tag: tag, Attrs: attrs, Children: kids}, nil
}

func skipSpace(s *scanner) {
	for {
		b := s.peek()
		if b == ' ' || b == '\t' || b == '\n' || b == '\r' {
			s.next()
			continue
		}
		break
	}
}

func parseAttr(s *scanner) (ast.Attr, error) {
	start := s.i
	for {
		b := s.peek()
		if (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z') || (b >= '0' && b <= '9') || b == '-' || b == '_' {
			s.next()
			continue
		}
		break
	}
	key := string(s.src[start:s.i])
	skipSpace(s)

	if s.peek() == '?' && s.peekN(1) == '=' {
		return ast.Attr{}, fmt.Errorf("unsupported ?= syntax for attribute %q; use {If(cond, Attr(...))} instead", key)
	}

	if s.peek() != '=' {
		return ast.Attr{Key: key, Kind: ast.AttrBool}, nil
	}
	s.next()
	skipSpace(s)
	switch s.peek() {
	case '"':
		s.next()
		vstart := s.i
		for !s.eof() && s.peek() != '"' {
			s.next()
		}
		val := string(s.src[vstart:s.i])
		if s.peek() == '"' {
			s.next()
		}
		return ast.Attr{Key: key, Kind: ast.AttrString, Value: val}, nil
	case '{':
		expr, err := readBracedSource(s)
		if err != nil {
			return ast.Attr{}, err
		}
		expr, err = rewriteTagsInGoExpr(expr)
		if err != nil {
			return ast.Attr{}, err
		}
		return ast.Attr{Key: key, Kind: ast.AttrExpr, Value: strings.TrimSpace(expr)}, nil
	default:
		return ast.Attr{}, fmt.Errorf("expected attr value for %s", key)
	}
}

func rewriteTagsInGoExpr(expr string) (string, error) {
	s := &scanner{src: []byte(expr)}
	var out strings.Builder
	for !s.eof() {
		if s.startsWith("//") {
			out.WriteString(s.readLineComment())
			continue
		}
		if s.startsWith("/*") {
			out.WriteString(s.readBlockComment())
			continue
		}
		switch s.peek() {
		case '"':
			out.WriteString(s.readStringLit())
			continue
		case '\'':
			out.WriteString(s.readRuneLit())
			continue
		case '`':
			out.WriteString(s.readRawString())
			continue
		case '<':
			if b := s.peekN(1); isTagStart(b) {
				el, err := parseTagExpr(s)
				if err != nil {
					return "", err
				}
				ex, err := gomponents.LowerNodes([]ast.Node{el}, gomponents.Context{VarTypes: map[string]string{}})
				if err != nil {
					return "", err
				}
				clearTokenPos(ex)
				out.WriteString(formatExpr(ex))
				continue
			}
		}
		out.WriteByte(s.next())
	}
	return out.String(), nil
}

func formatExpr(e goast.Expr) string {
	fset := gotoken.NewFileSet()
	var buf bytes.Buffer
	_ = format.Node(&buf, fset, e)
	// Keep embedded expressions single-line to avoid go/printer inserting odd blank lines
	// when the expression later gets parsed as part of a larger file.
	return strings.Join(strings.Fields(strings.TrimSpace(buf.String())), " ")
}

func clearTokenPos(n any) {
	// go/printer uses token.Pos gaps to decide where to insert newlines.
	// Our lowered AST nodes often come from parser.ParseExpr() with a different
	// fileset, which can lead to weird blank lines when printing as part of the
	// larger generated file. Clearing token.Pos normalizes formatting.
	clearTokenPosRV(reflect.ValueOf(n), map[uintptr]bool{})
}

func clearTokenPosRV(v reflect.Value, seen map[uintptr]bool) {
	if !v.IsValid() {
		return
	}
	if v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return
		}
		ptr := v.Pointer()
		if ptr != 0 {
			if seen[ptr] {
				return
			}
			seen[ptr] = true
		}
		clearTokenPosRV(v.Elem(), seen)
		return
	}
	switch v.Kind() {
	case reflect.Struct:
		tPos := reflect.TypeOf(gotoken.Pos(0))
		for i := 0; i < v.NumField(); i++ {
			f := v.Field(i)
			if !f.CanSet() && f.Kind() != reflect.Pointer && f.Kind() != reflect.Slice && f.Kind() != reflect.Struct {
				continue
			}
			if f.Type() == tPos && f.CanSet() {
				f.SetInt(int64(gotoken.NoPos))
				continue
			}
			clearTokenPosRV(f, seen)
		}
	case reflect.Slice, reflect.Array:
		for i := 0; i < v.Len(); i++ {
			clearTokenPosRV(v.Index(i), seen)
		}
	case reflect.Interface:
		if !v.IsNil() {
			clearTokenPosRV(v.Elem(), seen)
		}
	}
}

func readBracedSource(s *scanner) (string, error) {
	if s.peek() != '{' {
		return "", fmt.Errorf("expected {")
	}
	s.next()
	start := s.i
	depth := 1
	for !s.eof() {
		b := s.next()
		switch b {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return string(s.src[start : s.i-1]), nil
			}
		case '"':
			// skip string literal
			for !s.eof() {
				c := s.next()
				if c == '\\' {
					_ = s.next()
					continue
				}
				if c == '"' {
					break
				}
			}
		case '\'':
			for !s.eof() {
				c := s.next()
				if c == '\\' {
					_ = s.next()
					continue
				}
				if c == '\'' {
					break
				}
			}
		case '`':
			for !s.eof() && s.next() != '`' {
			}
		}
	}
	return "", fmt.Errorf("unexpected EOF in braced expr")
}
