// Code generated by 'yaegi extract maragu.dev/gomponents'. DO NOT EDIT.

package symbols

import (
	"io"
	"maragu.dev/gomponents"
	"reflect"
)

func init() {
	Symbols["maragu.dev/gomponents/gomponents"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Attr":          reflect.ValueOf(gomponents.Attr),
		"AttributeType": reflect.ValueOf(gomponents.AttributeType),
		"El":            reflect.ValueOf(gomponents.El),
		"ElementType":   reflect.ValueOf(gomponents.ElementType),
		"If":            reflect.ValueOf(gomponents.If),
		"Iff":           reflect.ValueOf(gomponents.Iff),
		"Raw":           reflect.ValueOf(gomponents.Raw),
		"Rawf":          reflect.ValueOf(gomponents.Rawf),
		"Text":          reflect.ValueOf(gomponents.Text),
		"Textf":         reflect.ValueOf(gomponents.Textf),

		// type definitions
		"Group":    reflect.ValueOf((*gomponents.Group)(nil)),
		"Node":     reflect.ValueOf((*gomponents.Node)(nil)),
		"NodeFunc": reflect.ValueOf((*gomponents.NodeFunc)(nil)),
		"NodeType": reflect.ValueOf((*gomponents.NodeType)(nil)),

		// interface wrapper definitions
		"_Node": reflect.ValueOf((*_maragu_dev_gomponents_Node)(nil)),
	}
}

// _maragu_dev_gomponents_Node is an interface wrapper for Node type
type _maragu_dev_gomponents_Node struct {
	IValue  interface{}
	WRender func(w io.Writer) error
}

func (W _maragu_dev_gomponents_Node) Render(w io.Writer) error {
	return W.WRender(w)
}
