// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["append_multiline"] = func() Node {
		return AppendMultiline()
	}
}

func AppendMultiline() Node {
	var rows []Node
	rows = append(rows, html.Tr(html.Td(Text("hello"))))
	rows = append(rows, html.Tr(html.Td(Text("world"))))
	return html.Div(Group(rows))
}
