// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"
	html "maragu.dev/gomponents/html"
)

type panel struct {
	Open bool
}

func init() {
	GSXFunctions["bool_attrs"] = func() Node {
		return BoolAttrs(true, false, panel{Open: false}, 2)
	}
}

// BoolAttrs puts bool expressions on attributes gomponents has no boolean
// constructor for. Each renders bare when true and is left out when false.
func BoolAttrs(open bool, hidden bool, p panel, step int) Node {
	return html.Div(
		html.Details(If(open, Attr("open")), html.Summary(Text("a"))),
		html.Details(If(p.Open, Attr("open")), html.Summary(Text("b"))),
		html.Section(If(hidden, Attr("hidden")), If(!open, Attr("inert")), Text("c")),
		html.Form(If(step > 1, Attr("novalidate")), Text("d")),
		html.IFrame(If(open && !hidden, Attr("allowfullscreen"))),
	)
}
