// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	"github.com/kilianc/gsx/e2e/helpers"

	. "maragu.dev/gomponents"
	. "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["component_tags"] = func() Node {
		return ComponentTags()
	}
}

func Card(children ...Node) Node {
	return Div(Class("card"), Group(children))
}

func ComponentTags() Node {
	return Div(
		Card(Class("primary"), P(Text("hello"))),
		Card(),
		helpers.Wrapper(Span(Text("wrapped"))),
	)
}
