// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"

	"strconv"
)

func init() {
	GSXFunctions["conditional_attrs"] = func() Node {
		return ConditionalAttrs(false, true, true, 123)
	}
}

func ConditionalAttrs(disabled bool, required bool, showID bool, id int) Node {
	return html.Form(
		html.Input(
			If(disabled, html.Disabled()),
			If(required, html.Required()),
			If(showID, Attr("data-id", strconv.Itoa(id))),
		),
	)
}
