// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["conditional_classes"] = func() Node {
		return ConditionalClasses(true)
	}
}

func ConditionalClasses(active bool) Node {
	return html.Div(
		html.Class("btn extra"),
		If(active, html.Class("is-active")),
		Text("ok"),
	)
}
