// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	"strings"

	. "maragu.dev/gomponents"
	html "maragu.dev/gomponents/html"
)

// shout is the doc comment on the first declaration after the imports. It
// must stay here rather than move into the rewritten import block.
const shout = "hi"

func init() {
	GSXFunctions["doc_comments"] = func() Node {
		return DocComments()
	}
}

// DocComments renders shout upper-cased.
func DocComments() Node {
	return html.P(Text(strings.ToUpper(shout)))
}
