// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "github.com/kilianc/gsx/e2e/dotimport"

	. "maragu.dev/gomponents"
	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["dot_import"] = func() Node {
		return DotImportTest()
	}
}

func DotImportTest() Node {
	return html.Div(
		Section("Info", html.P(Text("content"))),
		EmptyState("no items"),
		Page(html.Span(Text("hello"))),
	)
}
