// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"
)

func init() {
	GSXFunctions["fragment_only"] = func() Node {
		return FragmentOnly(Text("a"), Text("b"))
	}
}

// FragmentOnly is the only markup in this file, and it is a fragment: nothing
// here calls into gomponents/html, so the generated file must not import it.
func FragmentOnly(a, b Node) Node {
	return Group{a, b}
}
