// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	"fmt"

	. "maragu.dev/gomponents"
	html "maragu.dev/gomponents/html"
	"math/rand"
)

func init() {
	GSXFunctions["go_code"] = func() Node {
		rand.Seed(1)
		return GoCode()
	}
}

func GoCode() Node {
	hello := "world"
	fmt.Println(hello)

	colors := []string{"red", "green", "blue"}
	for i, color := range colors {
		colors[i] = color + "!"
	}

	lis := listItems(colors)

	topClass := "top"
	top := html.Div(
		html.Class(topClass),
		html.P(Text("hello")),
		html.P(Text(hello)),
		html.Ul(Group(lis)),
	)

	bottomClass := "bottom"
	bottom := html.Div(
		html.Class(bottomClass),
		html.P(html.Class(getRandomClass()), Text("hello")),
		html.P(html.Class(getRandomClass()), Text(hello)),
		html.Ul(html.Class(getRandomClass()), Group(lis)),
	)

	return html.Div(top, bottom)
}

func getRandomClass() string {
	return fmt.Sprintf("class-%d", rand.Intn(100))
}

func listItems(colors []string) []Node {
	var lis []Node
	for _, color := range colors {
		lis = append(lis, html.Li(Text(color)))
	}
	return lis
}
