// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	html "maragu.dev/gomponents/html"
)

// lineBreak lowers to html.Br() and nothing else: no gomponents name appears
// in this file, so the generated file must not import gomponents.
var lineBreak = html.Br()
