// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["html_coverage"] = func() Node {
		return HTMLCoverage()
	}
}

// sharedAttrs is built once and spread onto several elements.
//
// This is plain Go rather than a tag expression, so gomponents/html helpers
// would need an explicit `html.` prefix here. The dot-imported core Attr is
// enough for the attributes this fixture needs.
func sharedAttrs() []Node {
	return []Node{Attr("class", "shared"), Attr("data-kind", "demo")}
}

// HTMLCoverage exercises elements and attributes that used to fall back to the
// untyped El("tag", ...) and Attr("name", v) forms, plus JSX attribute
// spellings and spread attributes.
func HTMLCoverage() Node {
	return html.Article(
		html.Table(
			html.THead(
				html.Tr(
					html.Th(html.Scope("col"), Text("Name")),
					html.Th(html.Scope("col"), Text("Role")),
				),
			),
			html.TBody(html.Tr(html.Td(Text("Ada")), html.Td(html.Em(Text("engineer"))))),
		),
		html.Figure(
			html.Img(html.Src("/a.png"), html.Alt("A"), html.Width("64"), html.Height("64")),
			html.FigCaption(
				Text("A caption with "),
				html.Strong(Text("bold")),
				Text(" and "),
				html.Code(Text("code")),
				Text("."),
			),
		),
		html.Label(html.For("email"), Text("Email")),
		html.Input(
			html.ID("email"),
			html.Type("email"),
			html.AutoComplete("off"),
			html.MaxLength("120"),
			html.Required(),
		),
		html.Div(html.Class("jsx-spelling"), Text("className is class")),
		html.Span(Group(sharedAttrs()), Text("spread one")),
		html.Button(
			html.Type("button"),
			Group(sharedAttrs()),
			html.Disabled(),
			Text("spread two"),
		),
		html.Details(
			Attr("open"),
			html.Summary(Text("More")),
			html.BlockQuote(html.CiteAttr("https://example.com"), Text("Quoted.")),
		),
	)
}
