// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["jsx_syntax"] = func() Node {
		return JSXSyntax("world")
	}
}

// JSXSyntax exercises the JSX-compatible syntax: fragments, comments, text
// whitespace normalization, and HTML entity decoding.
func JSXSyntax(name string) Node {
	return html.Div(
		Group{
			html.H1(Text("Fragments group siblings")),
			html.P(Text("without emitting a wrapper")),
		},
		html.P(
			Text("This sentence is written across three source lines but renders as one."),
		),
		html.Ul(html.Li(Text("one")), html.Li(Text("two"))),
		html.P(html.B(Text("bold")), Text(" then "), html.I(Text("italic"))),
		html.P(Text("Tom & Jerry <3 AB café")),
		html.Span(Text(name)),
	)
}
