// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["name_shadowing"] = func() Node {
		return NameShadowing()
	}
}

// Article, Code and Summary all collide with gomponents/html exports. A local
// declaration must win, exactly as it would in ordinary Go — otherwise calls to
// them inside a `{...}` splice are rewritten to html.Article, html.Code and
// html.Summary, and the generated file does not compile.
func Article(id string, body Node) Node {
	return html.Article(html.ID(id), body)
}

func Code(s string) Node {
	return html.Code(html.Class("inline"), Text(s))
}

// Summary is defined in a sibling file (helpers_shadowing.go) to prove that
// shadowing is resolved across the whole package, not just this file.

func NameShadowing() Node {
	return html.Div(
		Article("one", Code("shadowed")),
		Summary("from a sibling file"),
		html.Section(html.ID("plain"), html.Code(Text("a real element"))),
	)
}
