// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	"github.com/kilianc/gsx/e2e/helpers"

	. "maragu.dev/gomponents"
	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["nested_expr_context"] = func() Node {
		return NestedExprContext(true)
	}
}

// A tag nested inside a `{...}` splice must be lowered with the same type
// context as the tag it sits in. It used to be lowered against an empty
// context, so a Node-typed variable became Text(node) — which does not compile.
func NestedExprContext(show bool) Node {
	node := Text("node-typed-var")
	nodes := []Node{Text("a"), Text("b")}
	str := "string-typed-var"

	return html.Div(
		If(show, html.P(node)),
		If(show, html.Ul(Group(nodes))),
		If(show, html.Span(Text(str))),
		If(show, El("em", helpers.MakeNode("from-pkg"))),
		If(show, El("b", Text(helpers.MakeString("str-from-pkg")))),
	)
}
