// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	"fmt"

	"github.com/kilianc/gsx/e2e/helpers"

	. "maragu.dev/gomponents"
	. "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["node_expressions"] = func() Node {
		return NodeExpressions()
	}
}

func NodeExpressions() Node {
	// := from selector call returning Node (was wrapped in Text)
	child := helpers.MakeNode("hello")

	// := from local uppercase call returning Node (was wrapped in Text)
	local := MakeLocalNode("world")

	// strings must still be wrapped in Text
	name := "test"
	formatted := fmt.Sprintf("hi %s", name)

	return Div(
		child,
		local,
		helpers.MakeNode("direct"),
		Text(name),
		Text(formatted),
		Text(fmt.Sprintf("inline %s", name)),
	)
}

func MakeLocalNode(s string) Node {
	return Text(s)
}
