// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["pkg_collision"] = func() Node {
		return PkgCollision()
	}
}

// Header is a local component whose name collides with html.Header.
func Header(title string, children ...Node) Node {
	return html.Header(html.H1(Text(title)), Group(children))
}

func PkgCollision() Node {
	return html.Div(
		Header("Hello", html.P(Text("content"))),
		html.Header(html.P(Text("raw header"))),
	)
}
