// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["raw_string"] = func() Node {
		return RawString()
	}
}

// A raw string literal spliced into markup must survive byte for byte. The
// pretty-printer collapses generated Go onto one line and re-indents it to the
// call site; doing either inside a literal silently rewrites the program's data.
func RawString() Node {
	return html.Div(
		html.StyleEl(
			Text(
				`
.card {
  color: red;
}
`,
			),
		),
		html.Pre(
			Text(
				`line one
	line two, tab indented
line three`,
			),
		),
	)
}
