// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	"github.com/kilianc/gsx/e2e/helpers"

	. "maragu.dev/gomponents"
	html "maragu.dev/gomponents/html"
)

func SelectorString() Node {
	// non-stdlib selector returning string — must be wrapped in Text
	label := helpers.MakeString("hello")

	// non-stdlib selector returning Node — must NOT be wrapped
	child := helpers.MakeNode("world")

	return html.Div(
		html.Span(Text(label)),
		html.Span(Text(helpers.MakeString("inline"))),
		child,
		helpers.MakeNode("direct"),
	)
}
