// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["struct_fields"] = func() Node {
		return StructFields(PageData{
			Title: html.H1(Text("hello")),
		})
	}
}

type PageData struct {
	Title Node
}

func StructFields(d PageData) Node {
	return html.Div(d.Title)
}
