// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	"database/sql"

	"github.com/kilianc/gsx/e2e/helpers"

	. "maragu.dev/gomponents"
	html "maragu.dev/gomponents/html"
	"time"
)

func init() {
	GSXFunctions["typed_params_exotic"] = func() Node {
		return TypedParamsExotic()
	}
}

func TypedParamsExotic() Node {
	now := time.Date(2025, 1, 15, 10, 30, 0, 0, time.UTC)
	link := helpers.LinkData{URL: "/details", Text: "View"}
	name := sql.NullString{String: "Alice", Valid: true}

	return html.Div(
		helpers.CellTime(now),
		helpers.CellLink(link),
		helpers.CellNullText(name),
		helpers.TimestampSection(now, html.P(Text("event details"))),
	)
}
