// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	"github.com/kilianc/gsx/e2e/helpers"

	. "maragu.dev/gomponents"
	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["typed_params"] = func() Node {
		return TypedParams()
	}
}

func TypedParams() Node {
	return html.Div(
		helpers.SectionHeading("Debug"),
		helpers.Badge("Active", "success"),
		helpers.SectionWithHeading("Info", html.P(Text("content"))),
		helpers.StatusDot(true),
		helpers.EmptyState("No items found"),
	)
}
