// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package e2e

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func init() {
	GSXFunctions["var_scoping"] = func() Node {
		return VarScoping()
	}
}

// VarScoping's `account` local is a Node and `items` is a []Node. Splice type
// inference must resolve both from THIS function's scope: UnrelatedAccount
// below reuses `account` as a plain string param, and before inference was
// scoped per function that name leaked file-wide and re-typed the splice here
// as a string, wrapping it in Text and breaking the build.
func VarScoping() Node {
	account := html.Span(html.Class("badge"), Text("acct"))
	items := nodeItems()
	return html.Div(account, html.Ul(Group(items)), UnrelatedAccount(true, "u-1"))
}

// UnrelatedAccount reuses the name `account` for a string param that is never
// spliced. It must not affect how VarScoping's `{account}` is lowered.
func UnrelatedAccount(ok bool, account string) Node {
	msg := "subscription for " + account
	if !ok {
		msg = "no subscription"
	}
	return html.P(Text(msg))
}

// nodeItems exercises []Node return-type inference: VarScoping's `items` must
// come from this signature, not from `out` leaking across function bodies.
func nodeItems() []Node {
	var out []Node
	for _, s := range []string{"a", "b"} {
		out = append(out, html.Li(Text(s)))
	}
	return out
}
