// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package ui

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func Cart(items []Item) Node {
	var rows []Node
	for _, it := range items {
		class := "row"
		if it.Sale {
			class += " sale"
		}
		rows = append(rows, html.Li(html.Class(class), Text(it.Name)))
	}
	return html.Ul(html.Class("cart"), Group(rows))
}
