// Code generated by gsxgo. Edits may be overwritten on regen.
//lint:file-ignore ST1001 dot imports are required in generated code

package ui

import (
	. "maragu.dev/gomponents"

	html "maragu.dev/gomponents/html"
)

func Greeting(name string) Node {
	return html.Main(
		html.Class("page"),
		html.H1(Text("Hello, "), Text(name), Text("!")),
		html.P(Text("Welcome to GSX.")),
	)
}
